# `fetch_experiment_runs` — Function Tests

Tests all combinations of the `include_summary_metrics` parameter and state filtering (passed via the `filters` dict).
Each section runs one variant and prints shape + column info so the results can be compared.

In [1]:
from src.utils.config import fetch_experiment_runs

# Fixed filters used across all tests — narrow to matrix_factorization runs only
BASE_FILTERS = {"config.model": "matrix_factorization"}

## Test 1 — Default behaviour (no state filter, no summary metrics)

Baseline: should behave identically to the old function.
Expected: returns all runs regardless of state, no `summary_metrics` column.

In [2]:
default_runs = fetch_experiment_runs(BASE_FILTERS)

print(f"Shape: {default_runs.shape}")
print(f"Columns: {default_runs.columns}")
assert "summary_metrics" not in default_runs.columns, "summary_metrics should NOT be present in default mode"
print("✓ No summary_metrics column")
default_runs.head(3)

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Fetched 256 runs...
Fetched 512 runs...
Fetched 768 runs...
Fetched 1024 runs...
Fetched 1280 runs...
Fetched 1536 runs...
Fetched 1792 runs...
Fetched 2048 runs...
Fetched 2304 runs...
Fetched 2560 runs...
Fetched 2816 runs...
Fetched 3072 runs...
Fetched 3328 runs...
Fetched 3390 runs...
Shape: (3390, 22)
Columns: ['id', 'name', 'model', 'config', 'shuffle', 'tracker', 'log_freq', 'max_epoch', 'batch_size', 'random_seed', 'store_model', 'learning_rate', 'early_stopping', 'l1_regularization', 'l2_regularization', 'evaluation_cutoffs', 'early_stopping_mode', 'embedding_dimension', 'early_stopping_monitor', 'embedding_dropout_rate', 'early_stopping_patience', 'config_collapse_method']
✓ No summary_metrics column

shape: (3, 22)
┌─────────────────────────────────┬──────────┬──────────────────────┬─────────────────────────────────┬───┬────────────────────────┬────────────────────────┬─────────────────────────┬────────────────────────┐
│ id                              ┆ name     ┆ model                ┆ config                          ┆ … ┆ early_stopping_monitor ┆ embedding_dropout_rate ┆ early_stopping_patience ┆ config_collapse_method │
│ ---                             ┆ ---      ┆ ---                  ┆ ---                             ┆   ┆ ---                    ┆ ---                    ┆ ---                     ┆ ---                    │
│ str                             ┆ str      ┆ str                  ┆ str                             ┆   ┆ str                    ┆ f64                    ┆ i64                     ┆ str                    │
╞═════════════════════════════════╪══════════╪══════════════════════╪═════════════════════════════════╪═══╪════════════════════════╪════════════════════════╪═════════════════════════╪════════════════════════╡
│ UnVuOnYxOjhrdnhvZGNqOnBlcHBlcm… ┆ 8kvxodcj ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ test_recall@10         ┆ 0.9                    ┆ 0                       ┆ null                   │
│ UnVuOnYxOnR6YzEzcnB0OnBlcHBlcm… ┆ tzc13rpt ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ test_recall@10         ┆ 0.9                    ┆ 0                       ┆ null                   │
│ UnVuOnYxOms2bXp0NmthOnBlcHBlcm… ┆ k6mzt6ka ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ test_recall@10         ┆ 0.8                    ┆ 0                       ┆ null                   │
└─────────────────────────────────┴──────────┴──────────────────────┴─────────────────────────────────┴───┴────────────────────────┴────────────────────────┴─────────────────────────┴────────────────────────┘

## Test 2 — State filter via filters dict (`"state": "finished"`)

Expected: returns fewer rows than Test 1 (only finished runs).
No `summary_metrics` column.

In [3]:
finished_runs = fetch_experiment_runs({**BASE_FILTERS, "state": "finished"})

print(f"Shape: {finished_runs.shape}")
print(f"All runs:    {default_runs.shape[0]}")
print(f"Finished:    {finished_runs.shape[0]}")
print(f"Difference:  {default_runs.shape[0] - finished_runs.shape[0]} (non-finished runs filtered out)")
assert finished_runs.shape[0] <= default_runs.shape[0], "Finished runs should be <= all runs"
assert "summary_metrics" not in finished_runs.columns, "summary_metrics should NOT be present"
print("✓ Row count reduced or equal")
print("✓ No summary_metrics column")
finished_runs.head(3)

Fetched 256 runs...
Fetched 512 runs...
Fetched 768 runs...
Fetched 1024 runs...
Fetched 1280 runs...
Fetched 1536 runs...
Fetched 1792 runs...
Fetched 2048 runs...
Fetched 2304 runs...
Fetched 2560 runs...
Fetched 2816 runs...
Fetched 3072 runs...
Fetched 3328 runs...
Fetched 3390 runs...
Shape: (3390, 22)
All runs:    3390
Finished:    3390
Difference:  0 (non-finished runs filtered out)
✓ Row count reduced or equal
✓ No summary_metrics column

shape: (3, 22)
┌─────────────────────────────────┬──────────┬──────────────────────┬─────────────────────────────────┬───┬────────────────────────┬────────────────────────┬─────────────────────────┬────────────────────────┐
│ id                              ┆ name     ┆ model                ┆ config                          ┆ … ┆ early_stopping_monitor ┆ embedding_dropout_rate ┆ early_stopping_patience ┆ config_collapse_method │
│ ---                             ┆ ---      ┆ ---                  ┆ ---                             ┆   ┆ ---                    ┆ ---                    ┆ ---                     ┆ ---                    │
│ str                             ┆ str      ┆ str                  ┆ str                             ┆   ┆ str                    ┆ f64                    ┆ i64                     ┆ str                    │
╞═════════════════════════════════╪══════════╪══════════════════════╪═════════════════════════════════╪═══╪════════════════════════╪════════════════════════╪═════════════════════════╪════════════════════════╡
│ UnVuOnYxOjhrdnhvZGNqOnBlcHBlcm… ┆ 8kvxodcj ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ test_recall@10         ┆ 0.9                    ┆ 0                       ┆ null                   │
│ UnVuOnYxOnR6YzEzcnB0OnBlcHBlcm… ┆ tzc13rpt ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ test_recall@10         ┆ 0.9                    ┆ 0                       ┆ null                   │
│ UnVuOnYxOms2bXp0NmthOnBlcHBlcm… ┆ k6mzt6ka ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ test_recall@10         ┆ 0.8                    ┆ 0                       ┆ null                   │
└─────────────────────────────────┴──────────┴──────────────────────┴─────────────────────────────────┴───┴────────────────────────┴────────────────────────┴─────────────────────────┴────────────────────────┘

## Test 3 — Summary metrics only (no state filter)

Expected: returns all runs (same count as Test 1), with a `summary_metrics` column present.
Inspect the column contents to verify the JSON is parsed correctly.

In [4]:
with_summary_runs = fetch_experiment_runs(BASE_FILTERS, include_summary_metrics=True)

print(f"Shape: {with_summary_runs.shape}")
assert with_summary_runs.shape[0] == default_runs.shape[0], "Row count should match default (no state filter)"
assert "epoch/test_recall@10" in with_summary_runs.columns, "epoch metrics should be present as flat columns"
print("✓ Row count matches default")
print("✓ epoch metric columns present")

# Show all epoch/* columns
epoch_cols = [c for c in with_summary_runs.columns if c.startswith("epoch/")]
print(f"\nEpoch metric columns ({len(epoch_cols)}): {epoch_cols}")

# Renamed metadata columns
for col in ["runtime", "step", "timestamp"]:
    present = col in with_summary_runs.columns
    print(f"  {col}: {'✓' if present else '✗'}")

with_summary_runs.head(3)

Fetched 256 runs...
Fetched 512 runs...
Fetched 768 runs...
Fetched 1024 runs...
Fetched 1280 runs...
Fetched 1536 runs...
Fetched 1792 runs...
Fetched 2048 runs...
Fetched 2304 runs...
Fetched 2560 runs...
Fetched 2816 runs...
Fetched 3072 runs...
Fetched 3328 runs...
Fetched 3390 runs...
Shape: (3390, 78)
✓ Row count matches default
✓ epoch metric columns present

Epoch metric columns (53): ['epoch/epoch', 'epoch/learning_rate', 'epoch/step_delta', 'epoch/test_hitrate@10', 'epoch/test_hitrate@2', 'epoch/test_hitrate@20', 'epoch/test_hitrate@50', 'epoch/test_loss', 'epoch/test_map@10', 'epoch/test_map@2', 'epoch/test_map@20', 'epoch/test_map@50', 'epoch/test_mrr@10', 'epoch/test_mrr@2', 'epoch/test_mrr@20', 'epoch/test_mrr@50', 'epoch/test_ndcg@10', 'epoch/test_ndcg@2', 'epoch/test_ndcg@20', 'epoch/test_ndcg@50', 'epoch/test_precision@10', 'epoch/test_precision@2', 'epoch/test_precision@20', 'epoch/test_precision@50', 'epoch/test_recall@10', 'epoch/test_recall@2', 'epoch/test_recall@20', 'epoch/test_recall@50', 'epoch/train_hitrate@10', 'epoch/train_hitrate@2', 'epoch/train_hitrate@20', 'epoch/train_hitrate@50', 'epoch/train_loss', 'epoch/train_map@10', 'epoch/train_map@2', 'epoch/train_map@20', 'epoch/train_map@50', 'epoch/train_mrr@10', 'epoch/train_mrr@2', 'epoch/train_mrr@20', 'epoch/train_mrr@50', 'epoch/train_ndcg@10', 'epoch/train_ndcg@2', 'epoch/train_ndcg@20', 'epoch/train_ndcg@50', 'epoch/train_precision@10', 'epoch/train_precision@2', 'epoch/train_precision@20', 'epoch/train_precision@50', 'epoch/train_recall@10', 'epoch/train_recall@2', 'epoch/train_recall@20', 'epoch/train_recall@50']
  runtime: ✓
  step: ✓
  timestamp: ✓

shape: (3, 78)
┌─────────────────────────────────┬──────────┬──────────────────────┬─────────────────────────────────┬───┬──────────────────────┬───────────────────────┬───────────────────────┬────────────────────────┐
│ id                              ┆ name     ┆ model                ┆ config                          ┆ … ┆ epoch/train_recall@2 ┆ epoch/train_recall@20 ┆ epoch/train_recall@50 ┆ config_collapse_method │
│ ---                             ┆ ---      ┆ ---                  ┆ ---                             ┆   ┆ ---                  ┆ ---                   ┆ ---                   ┆ ---                    │
│ str                             ┆ str      ┆ str                  ┆ str                             ┆   ┆ f64                  ┆ f64                   ┆ f64                   ┆ str                    │
╞═════════════════════════════════╪══════════╪══════════════════════╪═════════════════════════════════╪═══╪══════════════════════╪═══════════════════════╪═══════════════════════╪════════════════════════╡
│ UnVuOnYxOjhrdnhvZGNqOnBlcHBlcm… ┆ 8kvxodcj ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ 0.000607             ┆ 0.004774              ┆ 0.005643              ┆ null                   │
│ UnVuOnYxOnR6YzEzcnB0OnBlcHBlcm… ┆ tzc13rpt ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ 0.000607             ┆ 0.004774              ┆ 0.005643              ┆ null                   │
│ UnVuOnYxOms2bXp0NmthOnBlcHBlcm… ┆ k6mzt6ka ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ 0.000607             ┆ 0.004774              ┆ 0.005643              ┆ null                   │
└─────────────────────────────────┴──────────┴──────────────────────┴─────────────────────────────────┴───┴──────────────────────┴───────────────────────┴───────────────────────┴────────────────────────┘

## Test 4 — State filter + `include_summary_metrics=True` (the model_based_parse_params call pattern)

This is the exact combination that `model_based_parse_params` will use in production.
Expected: same row count as Test 2, with `summary_metrics` present and non-null for all rows (finished runs should always have metrics).

In [5]:
finished_with_summary = fetch_experiment_runs({**BASE_FILTERS, "state": "finished"}, include_summary_metrics=True)

print(f"Shape: {finished_with_summary.shape}")
assert finished_with_summary.shape[0] == finished_runs.shape[0], "Row count should match state='finished' result"
assert "epoch/test_recall@10" in finished_with_summary.columns, "epoch metrics should be present as flat columns"
print("✓ Row count matches finished-only result")
print("✓ epoch metric columns present")

null_count = finished_with_summary["epoch/test_recall@10"].null_count()
print(f"\nRuns with null epoch/test_recall@10: {null_count} / {finished_with_summary.shape[0]}")
if null_count > 0:
    print("⚠ Some finished runs are missing the target metric")
else:
    print("✓ All finished runs have epoch/test_recall@10 populated")
finished_with_summary.head(3)

Fetched 256 runs...
Fetched 512 runs...
Fetched 768 runs...
Fetched 1024 runs...
Fetched 1280 runs...
Fetched 1536 runs...
Fetched 1792 runs...
Fetched 2048 runs...
Fetched 2304 runs...
Fetched 2560 runs...
Fetched 2816 runs...
Fetched 3072 runs...
Fetched 3328 runs...
Fetched 3390 runs...
Shape: (3390, 78)
✓ Row count matches finished-only result
✓ epoch metric columns present

Runs with null epoch/test_recall@10: 0 / 3390
✓ All finished runs have epoch/test_recall@10 populated

shape: (3, 78)
┌─────────────────────────────────┬──────────┬──────────────────────┬─────────────────────────────────┬───┬──────────────────────┬───────────────────────┬───────────────────────┬────────────────────────┐
│ id                              ┆ name     ┆ model                ┆ config                          ┆ … ┆ epoch/train_recall@2 ┆ epoch/train_recall@20 ┆ epoch/train_recall@50 ┆ config_collapse_method │
│ ---                             ┆ ---      ┆ ---                  ┆ ---                             ┆   ┆ ---                  ┆ ---                   ┆ ---                   ┆ ---                    │
│ str                             ┆ str      ┆ str                  ┆ str                             ┆   ┆ f64                  ┆ f64                   ┆ f64                   ┆ str                    │
╞═════════════════════════════════╪══════════╪══════════════════════╪═════════════════════════════════╪═══╪══════════════════════╪═══════════════════════╪═══════════════════════╪════════════════════════╡
│ UnVuOnYxOjhrdnhvZGNqOnBlcHBlcm… ┆ 8kvxodcj ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ 0.000607             ┆ 0.004774              ┆ 0.005643              ┆ null                   │
│ UnVuOnYxOnR6YzEzcnB0OnBlcHBlcm… ┆ tzc13rpt ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ 0.000607             ┆ 0.004774              ┆ 0.005643              ┆ null                   │
│ UnVuOnYxOms2bXp0NmthOnBlcHBlcm… ┆ k6mzt6ka ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ 0.000607             ┆ 0.004774              ┆ 0.005643              ┆ null                   │
└─────────────────────────────────┴──────────┴──────────────────────┴─────────────────────────────────┴───┴──────────────────────┴───────────────────────┴───────────────────────┴────────────────────────┘

In [6]:
# Inspect a sample row — metric values and renamed metadata fields
finished_with_summary.select(
    ["id", "name", "runtime", "step", "timestamp", "epoch/test_recall@10", "epoch/test_recall@20"]
).head(3)

shape: (3, 7)
┌─────────────────────────────────┬──────────┬─────────┬──────┬───────────┬──────────────────────┬──────────────────────┐
│ id                              ┆ name     ┆ runtime ┆ step ┆ timestamp ┆ epoch/test_recall@10 ┆ epoch/test_recall@20 │
│ ---                             ┆ ---      ┆ ---     ┆ ---  ┆ ---       ┆ ---                  ┆ ---                  │
│ str                             ┆ str      ┆ i64     ┆ i64  ┆ f64       ┆ f64                  ┆ f64                  │
╞═════════════════════════════════╪══════════╪═════════╪══════╪═══════════╪══════════════════════╪══════════════════════╡
│ UnVuOnYxOjhrdnhvZGNqOnBlcHBlcm… ┆ 8kvxodcj ┆ 928     ┆ 63   ┆ 1.7746e9  ┆ 0.001259             ┆ 0.003466             │
│ UnVuOnYxOnR6YzEzcnB0OnBlcHBlcm… ┆ tzc13rpt ┆ 1088    ┆ 63   ┆ 1.7746e9  ┆ 0.001259             ┆ 0.003466             │
│ UnVuOnYxOms2bXp0NmthOnBlcHBlcm… ┆ k6mzt6ka ┆ 966     ┆ 63   ┆ 1.7746e9  ┆ 0.001259             ┆ 0.003466             │
└─────────────────────────────────┴──────────┴─────────┴──────┴───────────┴──────────────────────┴──────────────────────┘

## Test 5 — Config filters combined with state filter

Verify that `config.*` filters and `state` filter work together correctly.
Use a narrow filter (specific embedding_dimension) to get a small, fast result.

In [7]:
lower_embedding_runs = fetch_experiment_runs(
    {
        "config.model": "matrix_factorization",
        "config.embedding_dimension": 64,
        "state": "finished",
    },
    include_summary_metrics=True,
)

print(f"Shape: {lower_embedding_runs.shape}")
print(f"Unique embedding_dimension values: {lower_embedding_runs['embedding_dimension'].unique().to_list()}")
assert all(v == 64 for v in lower_embedding_runs["embedding_dimension"].to_list()), "All rows should have embedding_dimension=64"
print("✓ Config filter applied correctly alongside state filter")
lower_embedding_runs.head(3)

Fetched 256 runs...
Fetched 361 runs...
Shape: (361, 77)
Unique embedding_dimension values: [64]
✓ Config filter applied correctly alongside state filter

shape: (3, 77)
┌─────────────────────────────────┬──────────┬──────────────────────┬─────────────────────────────────┬───┬───────────────────────┬──────────────────────┬───────────────────────┬───────────────────────┐
│ id                              ┆ name     ┆ model                ┆ config                          ┆ … ┆ epoch/train_recall@10 ┆ epoch/train_recall@2 ┆ epoch/train_recall@20 ┆ epoch/train_recall@50 │
│ ---                             ┆ ---      ┆ ---                  ┆ ---                             ┆   ┆ ---                   ┆ ---                  ┆ ---                   ┆ ---                   │
│ str                             ┆ str      ┆ str                  ┆ str                             ┆   ┆ f64                   ┆ f64                  ┆ f64                   ┆ f64                   │
╞═════════════════════════════════╪══════════╪══════════════════════╪═════════════════════════════════╪═══╪═══════════════════════╪══════════════════════╪═══════════════════════╪═══════════════════════╡
│ UnVuOnYxOjdyaG5scDhxOnBlcHBlcm… ┆ 7rhnlp8q ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ 0.045642              ┆ 0.011296             ┆ 0.079572              ┆ 0.158306              │
│ UnVuOnYxOnd5emtjMDFsOnBlcHBlcm… ┆ wyzkc01l ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ 0.046225              ┆ 0.011796             ┆ 0.080519              ┆ 0.161265              │
│ UnVuOnYxOmpiNnRqbTA1OnBlcHBlcm… ┆ jb6tjm05 ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ 0.00024               ┆ 0.000056             ┆ 0.000476              ┆ 0.001155              │
└─────────────────────────────────┴──────────┴──────────────────────┴─────────────────────────────────┴───┴───────────────────────┴──────────────────────┴───────────────────────┴───────────────────────┘