# `fetch_experiment_runs` — Function Tests

Tests all combinations of the `include_summary_metrics` parameter and state filtering (passed via the `filters` dict).
Each section runs one variant and prints shape + column info so the results can be compared.

In [2]:
from src.utils.config import fetch_experiment_runs

# Fixed filters used across all tests — narrow to matrix_factorization runs only
BASE_FILTERS = {"model": "matrix_factorization"}

## Test 1 — Default behaviour (no state filter, no summary metrics)

Baseline: should behave identically to the old function.
Expected: returns all runs regardless of state, no `summary_metrics` column.

In [3]:
df_default = fetch_experiment_runs(BASE_FILTERS)

print(f"Shape: {df_default.shape}")
print(f"Columns: {df_default.columns}")
assert "summary_metrics" not in df_default.columns, "summary_metrics should NOT be present in default mode"
print("✓ No summary_metrics column")
df_default.head(3)

wandb: [wandb.Api()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Fetched 256 runs...
Fetched 512 runs...
Fetched 768 runs...
Fetched 1024 runs...
Fetched 1280 runs...
Fetched 1536 runs...
Fetched 1792 runs...
Fetched 2048 runs...
Fetched 2304 runs...
Fetched 2560 runs...
Fetched 2816 runs...
Fetched 3072 runs...
Fetched 3328 runs...
Fetched 3390 runs...
Shape: (3390, 22)
Columns: ['id', 'name', 'model', 'config', 'shuffle', 'tracker', 'log_freq', 'max_epoch', 'batch_size', 'random_seed', 'store_model', 'learning_rate', 'early_stopping', 'l1_regularization', 'l2_regularization', 'evaluation_cutoffs', 'early_stopping_mode', 'embedding_dimension', 'early_stopping_monitor', 'embedding_dropout_rate', 'early_stopping_patience', 'config_collapse_method']
✓ No summary_metrics column

shape: (3, 22)
┌─────────────────────────────────┬──────────┬──────────────────────┬─────────────────────────────────┬───┬────────────────────────┬────────────────────────┬─────────────────────────┬────────────────────────┐
│ id                              ┆ name     ┆ model                ┆ config                          ┆ … ┆ early_stopping_monitor ┆ embedding_dropout_rate ┆ early_stopping_patience ┆ config_collapse_method │
│ ---                             ┆ ---      ┆ ---                  ┆ ---                             ┆   ┆ ---                    ┆ ---                    ┆ ---                     ┆ ---                    │
│ str                             ┆ str      ┆ str                  ┆ str                             ┆   ┆ str                    ┆ f64                    ┆ i64                     ┆ str                    │
╞═════════════════════════════════╪══════════╪══════════════════════╪═════════════════════════════════╪═══╪════════════════════════╪════════════════════════╪═════════════════════════╪════════════════════════╡
│ UnVuOnYxOjhrdnhvZGNqOnBlcHBlcm… ┆ 8kvxodcj ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ test_recall@10         ┆ 0.9                    ┆ 0                       ┆ null                   │
│ UnVuOnYxOnR6YzEzcnB0OnBlcHBlcm… ┆ tzc13rpt ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ test_recall@10         ┆ 0.9                    ┆ 0                       ┆ null                   │
│ UnVuOnYxOms2bXp0NmthOnBlcHBlcm… ┆ k6mzt6ka ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ test_recall@10         ┆ 0.8                    ┆ 0                       ┆ null                   │
└─────────────────────────────────┴──────────┴──────────────────────┴─────────────────────────────────┴───┴────────────────────────┴────────────────────────┴─────────────────────────┴────────────────────────┘

## Test 2 — State filter via filters dict (`"state": "finished"`)

Expected: returns fewer rows than Test 1 (only finished runs).
No `summary_metrics` column.

In [4]:
df_finished = fetch_experiment_runs({**BASE_FILTERS, "state": "finished"})

print(f"Shape: {df_finished.shape}")
print(f"All runs:    {df_default.shape[0]}")
print(f"Finished:    {df_finished.shape[0]}")
print(f"Difference:  {df_default.shape[0] - df_finished.shape[0]} (non-finished runs filtered out)")
assert df_finished.shape[0] <= df_default.shape[0], "Finished runs should be <= all runs"
assert "summary_metrics" not in df_finished.columns, "summary_metrics should NOT be present"
print("✓ Row count reduced or equal")
print("✓ No summary_metrics column")
df_finished.head(3)

Fetched 256 runs...
Fetched 512 runs...
Fetched 768 runs...
Fetched 1024 runs...
Fetched 1280 runs...
Fetched 1536 runs...
Fetched 1792 runs...
Fetched 2048 runs...
Fetched 2304 runs...
Fetched 2560 runs...
Fetched 2816 runs...
Fetched 3072 runs...
Fetched 3328 runs...
Fetched 3390 runs...
Shape: (3390, 22)
All runs:    3390
Finished:    3390
Difference:  0 (non-finished runs filtered out)
✓ Row count reduced or equal
✓ No summary_metrics column

shape: (3, 22)
┌─────────────────────────────────┬──────────┬──────────────────────┬─────────────────────────────────┬───┬────────────────────────┬────────────────────────┬─────────────────────────┬────────────────────────┐
│ id                              ┆ name     ┆ model                ┆ config                          ┆ … ┆ early_stopping_monitor ┆ embedding_dropout_rate ┆ early_stopping_patience ┆ config_collapse_method │
│ ---                             ┆ ---      ┆ ---                  ┆ ---                             ┆   ┆ ---                    ┆ ---                    ┆ ---                     ┆ ---                    │
│ str                             ┆ str      ┆ str                  ┆ str                             ┆   ┆ str                    ┆ f64                    ┆ i64                     ┆ str                    │
╞═════════════════════════════════╪══════════╪══════════════════════╪═════════════════════════════════╪═══╪════════════════════════╪════════════════════════╪═════════════════════════╪════════════════════════╡
│ UnVuOnYxOjhrdnhvZGNqOnBlcHBlcm… ┆ 8kvxodcj ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ test_recall@10         ┆ 0.9                    ┆ 0                       ┆ null                   │
│ UnVuOnYxOnR6YzEzcnB0OnBlcHBlcm… ┆ tzc13rpt ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ test_recall@10         ┆ 0.9                    ┆ 0                       ┆ null                   │
│ UnVuOnYxOms2bXp0NmthOnBlcHBlcm… ┆ k6mzt6ka ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ test_recall@10         ┆ 0.8                    ┆ 0                       ┆ null                   │
└─────────────────────────────────┴──────────┴──────────────────────┴─────────────────────────────────┴───┴────────────────────────┴────────────────────────┴─────────────────────────┴────────────────────────┘

## Test 3 — Summary metrics only (no state filter)

Expected: returns all runs (same count as Test 1), with a `summary_metrics` column present.
Inspect the column contents to verify the JSON is parsed correctly.

In [5]:
df_with_summary = fetch_experiment_runs(BASE_FILTERS, include_summary_metrics=True)

print(f"Shape: {df_with_summary.shape}")
assert df_with_summary.shape[0] == df_default.shape[0], "Row count should match default (no state filter)"
assert "summary_metrics" in df_with_summary.columns, "summary_metrics column should be present"
print("✓ Row count matches default")
print("✓ summary_metrics column present")

# Inspect non-null summary_metrics rows
non_null = df_with_summary.filter(df_with_summary["summary_metrics"].is_not_null())
print(f"\nRuns with summary_metrics populated: {len(non_null)} / {len(df_with_summary)}")

# Show the keys available in a sample summary_metrics dict
if len(non_null) > 0:
    sample = non_null["summary_metrics"][0]
    print(f"\nSample summary_metrics keys:\n{sorted(sample.keys())}")
df_with_summary.head(3)

Fetched 256 runs...
Fetched 512 runs...
Fetched 768 runs...
Fetched 1024 runs...
Fetched 1280 runs...
Fetched 1536 runs...
Fetched 1792 runs...
Fetched 2048 runs...
Fetched 2304 runs...
Fetched 2560 runs...
Fetched 2816 runs...
Fetched 3072 runs...
Fetched 3328 runs...
Fetched 3390 runs...
Shape: (3390, 23)
✓ Row count matches default
✓ summary_metrics column present

Runs with summary_metrics populated: 3390 / 3390

Sample summary_metrics keys:
['_runtime', '_step', '_timestamp', '_wandb', 'epoch/epoch', 'epoch/learning_rate', 'epoch/step_delta', 'epoch/test_hitrate@10', 'epoch/test_hitrate@2', 'epoch/test_hitrate@20', 'epoch/test_hitrate@50', 'epoch/test_loss', 'epoch/test_map@10', 'epoch/test_map@2', 'epoch/test_map@20', 'epoch/test_map@50', 'epoch/test_mrr@10', 'epoch/test_mrr@2', 'epoch/test_mrr@20', 'epoch/test_mrr@50', 'epoch/test_ndcg@10', 'epoch/test_ndcg@2', 'epoch/test_ndcg@20', 'epoch/test_ndcg@50', 'epoch/test_precision@10', 'epoch/test_precision@2', 'epoch/test_precision@20', 'epoch/test_precision@50', 'epoch/test_recall@10', 'epoch/test_recall@2', 'epoch/test_recall@20', 'epoch/test_recall@50', 'epoch/train_hitrate@10', 'epoch/train_hitrate@2', 'epoch/train_hitrate@20', 'epoch/train_hitrate@50', 'epoch/train_loss', 'epoch/train_map@10', 'epoch/train_map@2', 'epoch/train_map@20', 'epoch/train_map@50', 'epoch/train_mrr@10', 'epoch/train_mrr@2', 'epoch/train_mrr@20', 'epoch/train_mrr@50', 'epoch/train_ndcg@10', 'epoch/train_ndcg@2', 'epoch/train_ndcg@20', 'epoch/train_ndcg@50', 'epoch/train_precision@10', 'epoch/train_precision@2', 'epoch/train_precision@20', 'epoch/train_precision@50', 'epoch/train_recall@10', 'epoch/train_recall@2', 'epoch/train_recall@20', 'epoch/train_recall@50']

shape: (3, 23)
┌─────────────────────────────────┬──────────┬──────────────────────┬─────────────────────────────────┬───┬────────────────────────┬─────────────────────────┬─────────────────────────────────┬────────────────────────┐
│ id                              ┆ name     ┆ model                ┆ config                          ┆ … ┆ embedding_dropout_rate ┆ early_stopping_patience ┆ summary_metrics                 ┆ config_collapse_method │
│ ---                             ┆ ---      ┆ ---                  ┆ ---                             ┆   ┆ ---                    ┆ ---                     ┆ ---                             ┆ ---                    │
│ str                             ┆ str      ┆ str                  ┆ str                             ┆   ┆ f64                    ┆ i64                     ┆ struct[57]                      ┆ str                    │
╞═════════════════════════════════╪══════════╪══════════════════════╪═════════════════════════════════╪═══╪════════════════════════╪═════════════════════════╪═════════════════════════════════╪════════════════════════╡
│ UnVuOnYxOjhrdnhvZGNqOnBlcHBlcm… ┆ 8kvxodcj ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ 0.9                    ┆ 0                       ┆ {928,63,1.7746e9,{928},63,0.01… ┆ null                   │
│ UnVuOnYxOnR6YzEzcnB0OnBlcHBlcm… ┆ tzc13rpt ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ 0.9                    ┆ 0                       ┆ {1088,63,1.7746e9,{1088},63,0.… ┆ null                   │
│ UnVuOnYxOms2bXp0NmthOnBlcHBlcm… ┆ k6mzt6ka ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ 0.8                    ┆ 0                       ┆ {966,63,1.7746e9,{966},63,0.01… ┆ null                   │
└─────────────────────────────────┴──────────┴──────────────────────┴─────────────────────────────────┴───┴────────────────────────┴─────────────────────────┴─────────────────────────────────┴────────────────────────┘

## Test 4 — State filter + `include_summary_metrics=True` (the model_based_parse_params call pattern)

This is the exact combination that `model_based_parse_params` will use in production.
Expected: same row count as Test 2, with `summary_metrics` present and non-null for all rows (finished runs should always have metrics).

In [6]:
df_full = fetch_experiment_runs({**BASE_FILTERS, "state": "finished"}, include_summary_metrics=True)

print(f"Shape: {df_full.shape}")
assert df_full.shape[0] == df_finished.shape[0], "Row count should match state='finished' result"
assert "summary_metrics" in df_full.columns, "summary_metrics column should be present"
print("✓ Row count matches finished-only result")
print("✓ summary_metrics column present")

non_null_full = df_full.filter(df_full["summary_metrics"].is_not_null())
null_count = df_full.shape[0] - len(non_null_full)
print(f"\nRuns with null summary_metrics: {null_count} / {df_full.shape[0]}")
if null_count > 0:
    print("⚠ Some finished runs have no summary_metrics — inspect these rows:")
    print(df_full.filter(df_full["summary_metrics"].is_null()).select(["id", "name"]))
else:
    print("✓ All finished runs have summary_metrics populated")
df_full.head(3)

Fetched 256 runs...
Fetched 512 runs...
Fetched 768 runs...
Fetched 1024 runs...
Fetched 1280 runs...
Fetched 1536 runs...
Fetched 1792 runs...
Fetched 2048 runs...
Fetched 2304 runs...
Fetched 2560 runs...
Fetched 2816 runs...
Fetched 3072 runs...
Fetched 3328 runs...
Fetched 3390 runs...
Shape: (3390, 23)
✓ Row count matches finished-only result
✓ summary_metrics column present

Runs with null summary_metrics: 0 / 3390
✓ All finished runs have summary_metrics populated

shape: (3, 23)
┌─────────────────────────────────┬──────────┬──────────────────────┬─────────────────────────────────┬───┬────────────────────────┬─────────────────────────┬─────────────────────────────────┬────────────────────────┐
│ id                              ┆ name     ┆ model                ┆ config                          ┆ … ┆ embedding_dropout_rate ┆ early_stopping_patience ┆ summary_metrics                 ┆ config_collapse_method │
│ ---                             ┆ ---      ┆ ---                  ┆ ---                             ┆   ┆ ---                    ┆ ---                     ┆ ---                             ┆ ---                    │
│ str                             ┆ str      ┆ str                  ┆ str                             ┆   ┆ f64                    ┆ i64                     ┆ struct[57]                      ┆ str                    │
╞═════════════════════════════════╪══════════╪══════════════════════╪═════════════════════════════════╪═══╪════════════════════════╪═════════════════════════╪═════════════════════════════════╪════════════════════════╡
│ UnVuOnYxOjhrdnhvZGNqOnBlcHBlcm… ┆ 8kvxodcj ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ 0.9                    ┆ 0                       ┆ {928,63,1.7746e9,{928},63,0.01… ┆ null                   │
│ UnVuOnYxOnR6YzEzcnB0OnBlcHBlcm… ┆ tzc13rpt ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ 0.9                    ┆ 0                       ┆ {1088,63,1.7746e9,{1088},63,0.… ┆ null                   │
│ UnVuOnYxOms2bXp0NmthOnBlcHBlcm… ┆ k6mzt6ka ┆ matrix_factorization ┆ configs/hyperparameter_search/… ┆ … ┆ 0.8                    ┆ 0                       ┆ {966,63,1.7746e9,{966},63,0.01… ┆ null                   │
└─────────────────────────────────┴──────────┴──────────────────────┴─────────────────────────────────┴───┴────────────────────────┴─────────────────────────┴─────────────────────────────────┴────────────────────────┘

In [7]:
df_full["summary_metrics"][0]

{'_runtime': 928,
 '_step': 63,
 '_timestamp': 1774598234.4881632,
 '_wandb': {'runtime': 928},
 'epoch/epoch': 63,
 'epoch/learning_rate': 0.009999999776482582,
 'epoch/step_delta': 8459,
 'epoch/test_hitrate@10': 0.011210054159164429,
 'epoch/test_hitrate@2': 0.0028104078955948353,
 'epoch/test_hitrate@20': 0.027630414813756943,
 'epoch/test_hitrate@50': 0.033630162477493286,
 'epoch/test_loss': 'NaN',
 'epoch/test_map@10': 0.002542325993999839,
 'epoch/test_map@2': 0.0014052039477974176,
 'epoch/test_map@20': 0.0035908168647438288,
 'epoch/test_map@50': 0.003773926757276058,
 'epoch/test_mrr@10': 0.002548904623836279,
 'epoch/test_mrr@2': 0.0014052039477974176,
 'epoch/test_mrr@20': 0.003633303800597787,
 'epoch/test_mrr@50': 0.0038182768039405346,
 'epoch/test_ndcg@10': 0.004512862302362919,
 'epoch/test_ndcg@2': 0.0017731725238263607,
 'epoch/test_ndcg@20': 0.00862340722233057,
 'epoch/test_ndcg@50': 0.009818012826144695,
 'epoch/test_precision@10': 0.0011589013738557696,
 'epoch/test_precision@2': 0.0014052039477974176,
 'epoch/test_precision@20': 0.001482571940869093,
 'epoch/test_precision@50': 0.0007237577228806913,
 'epoch/test_recall@10': 0.0012593806022778151,
 'epoch/test_recall@2': 0.0003188636328559369,
 'epoch/test_recall@20': 0.0034658212680369616,
 'epoch/test_recall@50': 0.004096944350749254,
 'epoch/train_hitrate@10': 0.05323986336588859,
 'epoch/train_hitrate@2': 0.018188707530498505,
 'epoch/train_hitrate@20': 0.11377415806055068,
 'epoch/train_hitrate@50': 0.1346469670534134,
 'epoch/train_loss': 'NaN',
 'epoch/train_map@10': 0.013549753464758396,
 'epoch/train_map@2': 0.009094353765249252,
 'epoch/train_map@20': 0.01713412068784237,
 'epoch/train_map@50': 0.017880834639072418,
 'epoch/train_mrr@10': 0.013945677317678928,
 'epoch/train_mrr@2': 0.009094353765249252,
 'epoch/train_mrr@20': 0.018102353438735008,
 'epoch/train_mrr@50': 0.01878066174685955,
 'epoch/train_ndcg@10': 0.02290817908942699,
 'epoch/train_ndcg@2': 0.011475794017314913,
 'epoch/train_ndcg@20': 0.03874116763472557,
 'epoch/train_ndcg@50': 0.04330531507730484,
 'epoch/train_precision@10': 0.00612605782225728,
 'epoch/train_precision@2': 0.009094353765249252,
 'epoch/train_precision@20': 0.00786756444722414,
 'epoch/train_precision@50': 0.003869522362947464,
 'epoch/train_recall@10': 0.001840240554884076,
 'epoch/train_recall@2': 0.0006073698750697076,
 'epoch/train_recall@20': 0.00477431109175086,
 'epoch/train_recall@50': 0.005643006414175034}

## Test 5 — Config filters combined with state filter

Verify that `config.*` filters and `state` filter work together correctly.
Use a narrow filter (specific embedding_dimension) to get a small, fast result.

In [ ]:
df_narrow = fetch_experiment_runs(
    {"model": "matrix_factorization", "embedding_dimension": 64, "state": "finished"},
    include_summary_metrics=True,
)

print(f"Shape: {df_narrow.shape}")
print(f"Unique embedding_dimension values: {df_narrow['embedding_dimension'].unique().to_list()}")
assert all(v == 64 for v in df_narrow["embedding_dimension"].to_list()), "All rows should have embedding_dimension=64"
print("✓ Config filter applied correctly alongside state filter")
df_narrow.head(3)