In [3]:
import os
import tqdm
import wandb
import warnings
import numpy as np
import pandas as pd
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import concurrent.futures

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'  # Suppress TensorFlow logging
warnings.filterwarnings('ignore', category=UserWarning, module='google.protobuf')

from matplotlib.axes import Axes
from wandb.apis.public import Run

from typing import Union, List, Dict
from src.visualization import set_themes
from IPython.display import Markdown

set_themes() # Set custom themes for plots
pl.Config.set_tbl_rows(20) # Set Polars table display rows limit

pd.set_option('future.no_silent_downcasting', True)

In [56]:
cache_file = "wandb/summary.parquet"
config = {
    "model": "matrix_factorization",
    "ensure_available_locally": False
}
sorting_criterion = {
    "epoch/test_hitrate@50": 0.5,
    "epoch/test_ndcg@50": 0.25,
}

if cache_file is not None and os.path.exists(cache_file):
    print(f"Loading cached experiment runs from {cache_file}...")
    experiment_runs = pl.read_parquet(cache_file)
    print(f"Loaded {len(experiment_runs)} runs from cache.")
else:
    print("No cache file found. Fetching experiment runs from Weights & Biases...")
    api = wandb.Api() # Initialize Weights & Biases API, used for fetching run data

    def fetch_run_metadata(run: Run, considered_metrics: Union[str, Dict[str, float]] = "epoch/epoch") -> Dict:
        run_config = {}
        for key, value in run.config.items():
            # Convert lists and dicts to strings
            if isinstance(value, (list, dict)):
                run_config[key] = str(value)
            else:
                run_config[key] = value

        run_history = run.history()
        run_history = run_history.replace({"Infinity": np.inf, "NaN": np.nan})

        if isinstance(considered_metrics, str):
            run_history["score"] = run_history[considered_metrics]
        elif isinstance(considered_metrics, dict):
            run_history["score"] = sum(
                run_history[metric] * weight for metric, weight in considered_metrics.items()
            )
        else:
            raise ValueError("considered_metrics must be either a string or a dictionary")
        
        best_summary = run_history.iloc[run_history["score"].argmax()]
        best_summary = {f"best:{key}": val for key, val in best_summary.items()}
        
        return {
            "run_id": run.id,
            "run_name": run.name,
            "sweep_id": run.sweep.id if run.sweep else None,
            "model": run.config.get("model"),
            **run_config,
            **{metric: run_history[metric].to_list() for metric in run_history},
            **best_summary,
            "gpu_type": run.metadata.get("gpu"),
            "cpu_count": run.metadata.get("cpu_count"),
        }

    batch_size = 16
    records = []
    futures = {}
    executor = concurrent.futures.ThreadPoolExecutor(max_workers=batch_size)
    runs:List[Run] = api.runs("feedr/peppermint-matrix", per_page=2*batch_size-1, filters={"config.model": config["model"]})
    run_iterator = iter(runs)
    with tqdm.tqdm(total=len(runs), ncols=128) as pbar:
        while len(records) < len(runs):
            # submit new tasks if we empty slots in the batch
            while len(futures) < batch_size and len(records) + len(futures) < len(runs):
                current_runs = next(run_iterator)
                current_future = executor.submit(fetch_run_metadata, current_runs, sorting_criterion)
                futures[current_future] = current_runs

            # check for completed tasks
            finished_futures, _ = concurrent.futures.wait(futures.keys(), return_when=concurrent.futures.FIRST_COMPLETED, timeout=0.1)
            for finished_future in finished_futures:
                finished_run = futures.pop(finished_future)
                records.append(finished_future.result())
                pbar.update(1)

    # Create a Polars DataFrame from the records
    experiment_runs = pl.DataFrame(records, infer_schema_length=None)
    
# Tag run as available locally if the model files exist
local_run_ids = []
local_sweep_ids = os.listdir(f"./models/{config['model']}/")
for sweep_id in local_sweep_ids:
    local_run_ids.extend([run_id for run_id in os.listdir(f"./models/{config['model']}/{sweep_id}/")])
    
experiment_runs = experiment_runs.with_columns(
    available_locally=pl.col("run_id").is_in(local_run_ids)
)

if config["ensure_available_locally"]:
    experiment_runs = experiment_runs.filter(pl.col("available_locally") == True)

experiment_runs = experiment_runs.sort("_timestamp", descending=False)
experiment_runs = experiment_runs.with_columns(
    run_duration_second=pl.col("_runtime").list.max(),
    run_duration_minute=(pl.col("_runtime").list.max() / 60)
)
experiment_runs.select(
    pl.col("run_id"),
    pl.col("run_name"),
    pl.col("sweep_id"),
    pl.col("model"),
    pl.col("embedding_dimension"),
    pl.col("shuffle"),
    pl.col("best:epoch/epoch"),
    pl.col("best:epoch/train_loss"),
    pl.col("best:epoch/test_loss"),
    pl.col("best:epoch/train_recall@10"),
    pl.col("best:epoch/train_ndcg@10"),
    pl.col("best:epoch/test_recall@10"),
    pl.col("best:epoch/test_ndcg@10"),
)

Loading cached experiment runs from wandb/summary.parquet...
Loaded 3602 runs from cache.

shape: (3_602, 13)
┌──────────┬────────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ run_id   ┆ run_name   ┆ sweep_id ┆ model     ┆ … ┆ best:epoc ┆ best:epoc ┆ best:epoc ┆ best:epoc │
│ ---      ┆ ---        ┆ ---      ┆ ---       ┆   ┆ h/train_r ┆ h/train_n ┆ h/test_re ┆ h/test_nd │
│ str      ┆ str        ┆ str      ┆ str       ┆   ┆ ecall@10  ┆ dcg@10    ┆ call@10   ┆ cg@10     │
│          ┆            ┆          ┆           ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆            ┆          ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞══════════╪════════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ o94q0juk ┆ logical-sw ┆ nbysw136 ┆ matrix_fa ┆ … ┆ 0.035844  ┆ 0.359888  ┆ 0.026077  ┆ 0.100539  │
│          ┆ eep-1      ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ 4ftaae0p ┆ stilted-sw ┆ nbysw136 ┆ matrix_fa ┆ … ┆ 0.007561  ┆ 0.085169  ┆ 0.006594  ┆ 0.02556   │
│          ┆ eep-3      ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ fway5u2z ┆ breezy-swe ┆ nbysw136 ┆ matrix_fa ┆ … ┆ 0.00596   ┆ 0.065856  ┆ 0.0026    ┆ 0.012059  │
│          ┆ ep-4       ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ bphcl2xf ┆ clean-swee ┆ nbysw136 ┆ matrix_fa ┆ … ┆ 0.162349  ┆ 0.79712   ┆ 0.024744  ┆ 0.095121  │
│          ┆ p-2        ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ fftz1dek ┆ trim-sweep ┆ nbysw136 ┆ matrix_fa ┆ … ┆ 0.035769  ┆ 0.356031  ┆ 0.025562  ┆ 0.099834  │
│          ┆ -5         ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ otb8suw9 ┆ scarlet-sw ┆ nbysw136 ┆ matrix_fa ┆ … ┆ 0.028667  ┆ 0.295834  ┆ 0.021467  ┆ 0.082659  │
│          ┆ eep-6      ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ lvre7srl ┆ solar-swee ┆ nbysw136 ┆ matrix_fa ┆ … ┆ 0.109647  ┆ 0.714525  ┆ 0.021456  ┆ 0.084617  │
│          ┆ p-7        ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ dcbj92eg ┆ ruby-sweep ┆ nbysw136 ┆ matrix_fa ┆ … ┆ 0.091837  ┆ 0.637288  ┆ 0.024295  ┆ 0.094158  │
│          ┆ -8         ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ x17mnyw8 ┆ breezy-swe ┆ nbysw136 ┆ matrix_fa ┆ … ┆ 0.034525  ┆ 0.346527  ┆ 0.023699  ┆ 0.089898  │
│          ┆ ep-9       ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ 7jrm756b ┆ super-swee ┆ nbysw136 ┆ matrix_fa ┆ … ┆ 0.003005  ┆ 0.043139  ┆ 0.002425  ┆ 0.010531  │
│          ┆ p-10       ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …          ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ pajbzkpy ┆ genial-for ┆ null     ┆ matrix_fa ┆ … ┆ 0.031591  ┆ 0.319264  ┆ 0.02347   ┆ 0.088763  │
│          ┆ est-4375   ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ cakp0s8f ┆ comfy-shad ┆ null     ┆ matrix_fa ┆ … ┆ 0.028159  ┆ 0.286681  ┆ 0.021564  ┆ 0.081569  │
│          ┆ ow-4376    ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ 6sthgm3k ┆ efficient- ┆ null     ┆ matrix_fa ┆ … ┆ 0.02864   ┆ 0.293071  ┆ 0.02147   ┆ 0.081138  │
│          ┆ plasma-437 ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆ 7          ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ sa8rftaq ┆ flowing-du ┆ null     ┆ matrix_fa ┆ … ┆ 0.024962  ┆ 0.265844  ┆ 0.01948   ┆ 0.074974  │
│          ┆ st-4378    ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ wi4tb7wd ┆ firm-snowb ┆ null     ┆ matrix_fa ┆ … ┆ 0.026158  ┆ 0.276935  ┆ 0.020669  ┆ 0.082644  │
│          ┆ all-4379   ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ t9f8r9yl ┆ youthful-w ┆ null     ┆ matrix_fa ┆ … ┆ 0.021356  ┆ 0.239728  ┆ 0.016967  ┆ 0.068005  │
│          ┆ ater-4380  ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ isxhqjp4 ┆ radiant-sh ┆ null     ┆ matrix_fa ┆ … ┆ 0.020638  ┆ 0.233397  ┆ 0.016542  ┆ 0.066734  │
│          ┆ ape-4381   ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ koi25lci ┆ crimson-re ┆ null     ┆ matrix_fa ┆ … ┆ 0.017374  ┆ 0.20561   ┆ 0.013844  ┆ 0.059412  │
│          ┆ sonance-43 ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆ 82         ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ mamdsyel ┆ logical-di ┆ null     ┆ matrix_fa ┆ … ┆ 0.017726  ┆ 0.208382  ┆ 0.014581  ┆ 0.059687  │
│          ┆ sco-4383   ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
│ 1tjfx5p9 ┆ mild-dew-4 ┆ null     ┆ matrix_fa ┆ … ┆ 0.001681  ┆ 0.02867   ┆ 0.001287  ┆ 0.006087  │
│          ┆ 384        ┆          ┆ ctorizati ┆   ┆           ┆           ┆           ┆           │
│          ┆            ┆          ┆ on        ┆   ┆           ┆           ┆           ┆           │
└──────────┴────────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

# High Level Parameter Comparison
We pick one parameter and then see its impact on the overall performance, setting the other parameters to their best values.

## Global Leaderboard
We can look at the global leaderboard to find the best parameters. 
Here we average performance across random seeds.

**Verdict**:  
The best parameters are `embedding_dimension=512` and regulariaztion strength of 1e-7 for both l2 and l1 regularization.

In [58]:
global_leaderboard = experiment_runs.filter(
    # pl.col("shuffle") == False,
    # pl.col("embedding_dimension") == 64,
    # pl.col("l1_regularization") == 0.0,
    # pl.col("l2_regularization") == 0.0,
    # pl.col("embedding_dropout_rate") == 0.0
).group_by( # group over random_seed runs
    "shuffle", "embedding_dimension", "l2_regularization", "l1_regularization", "embedding_dropout_rate"
).agg(
    pl.col("run_id").count().alias("num_runs"),
    pl.col("best:epoch/epoch").mean(),
    pl.col("best:epoch/test_recall@10").mean(),
    pl.col("best:epoch/test_ndcg@10").mean(),
    pl.col("best:epoch/train_recall@20").mean(),
    pl.col("best:epoch/train_ndcg@20").mean(),
    pl.col("best:epoch/test_recall@20").mean(),
    pl.col("best:epoch/test_ndcg@20").mean(),
).sort(
    "best:epoch/test_recall@20", descending=True
).with_columns(
    pl.col("l1_regularization").cast(pl.Utf8),
    pl.col("l2_regularization").cast(pl.Utf8)
)
global_leaderboard.to_pandas()[:20]

,shuffle,embedding_dimension,l2_regularization,l1_regularization,embedding_dropout_rate,num_runs,best:epoch/epoch,best:epoch/test_recall@10,best:epoch/test_ndcg@10,best:epoch/train_recall@20,best:epoch/train_ndcg@20,best:epoch/test_recall@20,best:epoch/test_ndcg@20
0,False,512,1e-7,1e-7,0.0,2,54.500000,0.029229,0.110878,0.095795,0.495562,0.050826,0.139257
1,True,256,1e-7,1e-7,0.0,2,49.000000,0.029147,0.109712,0.096081,0.496097,0.050726,0.137957
2,False,1024,1e-7,1e-7,0.0,2,38.500000,0.029106,0.110862,0.096978,0.502766,0.050601,0.139435
3,False,256,1e-7,1e-7,0.0,4,56.000000,0.029069,0.110974,0.096712,0.497941,0.050331,0.138991
4,True,1024,1e-7,1e-7,0.0,2,48.500000,0.029038,0.109123,0.093976,0.488645,0.050271,0.137616
5,False,128,1e-7,1e-7,0.0,7,53.285714,0.028866,0.109814,0.096728,0.497861,0.050247,0.137913
6,True,512,1e-7,1e-7,0.0,2,33.500000,0.028948,0.109235,0.097426,0.501240,0.050233,0.137338
7,False,64,1e-7,1e-7,0.0,2,60.000000,0.028272,0.107800,0.093670,0.487896,0.049545,0.135976
8,True,128,1e-7,1e-7,0.0,2,54.000000,0.028584,0.107302,0.095482,0.494929,0.049522,0.135343
9,True,128,1e-7,1e-8,0.0,3,58.666667,0.028819,0.108966,0.158784,0.640584,0.049503,0.136560
10,False,128,1e-7,1e-8,0.0,5,57.000000,0.028454,0.107909,0.161297,0.644594,0.049477,0.136078
11,True,256,1e-7,1e-8,0.0,3,59.333333,0.028513,0.107848,0.198238,0.725113,0.049442,0.135895
12,False,256,1e-7,1e-8,0.0,2,58.500000,0.028487,0.109045,0.202501,0.726463,0.049366,0.136908
13,False,128,1e-7,1e-9,0.0,3,58.333333,0.028306,0.106719,0.168284,0.657009,0.049284,0.135038
14,True,64,1e-7,1e-7,0.0,2,54.000000,0.028294,0.108377,0.092422,0.484148,0.049247,0.136290
15,False,64,1e-7,1e-8,0.0,2,55.500000,0.028396,0.107867,0.118325,0.547508,0.048936,0.135445
16,False,64,1e-7,1e-9,0.0,4,57.500000,0.028132,0.106262,0.121399,0.553954,0.048820,0.134181
17,False,128,1e-7,0.0,0.0,13,55.538462,0.028144,0.106759,0.168395,0.658030,0.048783,0.134612
18,True,128,1e-7,1e-9,0.0,4,59.250000,0.028080,0.106225,0.166833,0.657817,0.048698,0.134506
19,True,128,1e-7,0.0,0.0,16,58.062500,0.028076,0.106437,0.167265,0.658314,0.048684,0.134407

## L2 Regularization Impact

In [78]:
experiment_summary = experiment_runs.filter(
    # pl.col("shuffle") == False,
    # pl.col("embedding_dimension") == 64,
    # pl.col("l1_regularization") == 0.0,
    # pl.col("l2_regularization") == 0.0,
    # pl.col("embedding_dropout_rate") == 0.0
).group_by( # group over random_seed runs
    "shuffle", "embedding_dimension", "l2_regularization", "l1_regularization"
).agg(
    pl.col("run_id").count().alias("num_runs"),
    pl.col("best:epoch/epoch").mean(),
    pl.col("best:epoch/test_recall@10").mean(),
    pl.col("best:epoch/test_ndcg@10").mean(),
    pl.col("best:epoch/test_recall@20").mean(),
    pl.col("best:epoch/test_ndcg@20").mean(),
).group_by( # group over unrelevant parameters, e.g., regularization
    "l2_regularization", "embedding_dimension"
).agg(
    pl.col("num_runs").sum(),
    pl.col("best:epoch/epoch").mean(),
    pl.col("best:epoch/test_recall@10").max(),
    pl.col("best:epoch/test_ndcg@10").max(),
    pl.col("best:epoch/test_recall@20").max(),
    pl.col("best:epoch/test_ndcg@20").max(),
).sort("l2_regularization", "embedding_dimension")

### Run Counts

In [79]:
experiment_summary[["embedding_dimension", "l2_regularization", "num_runs"]].pivot(
    values=["num_runs"],
    index="embedding_dimension",
    columns="l2_regularization"
)

/tmp/ipykernel_3771275/2842099446.py:1: DeprecationWarning: the argument `columns` for `DataFrame.pivot` is deprecated. It was renamed to `on` in version 1.0.0.
  experiment_summary[["embedding_dimension", "l2_regularization", "num_runs"]].pivot(

shape: (10, 11)
┌─────────────────────┬─────┬───────┬──────┬───┬─────────┬────────┬───────┬──────┐
│ embedding_dimension ┆ 0.0 ┆ 1e-10 ┆ 1e-9 ┆ … ┆ 0.00001 ┆ 0.0001 ┆ 0.001 ┆ 0.01 │
│ ---                 ┆ --- ┆ ---   ┆ ---  ┆   ┆ ---     ┆ ---    ┆ ---   ┆ ---  │
│ i64                 ┆ u32 ┆ u32   ┆ u32  ┆   ┆ u32     ┆ u32    ┆ u32   ┆ u32  │
╞═════════════════════╪═════╪═══════╪══════╪═══╪═════════╪════════╪═══════╪══════╡
│ 2                   ┆ 138 ┆ 7     ┆ 21   ┆ … ┆ 24      ┆ 19     ┆ 12    ┆ 10   │
│ 4                   ┆ 124 ┆ 5     ┆ 22   ┆ … ┆ 24      ┆ 27     ┆ 9     ┆ 10   │
│ 8                   ┆ 124 ┆ 13    ┆ 18   ┆ … ┆ 22      ┆ 21     ┆ 9     ┆ 10   │
│ 16                  ┆ 121 ┆ 5     ┆ 17   ┆ … ┆ 24      ┆ 26     ┆ 9     ┆ 10   │
│ 32                  ┆ 112 ┆ 5     ┆ 17   ┆ … ┆ 22      ┆ 24     ┆ 12    ┆ 15   │
│ 64                  ┆ 109 ┆ 8     ┆ 38   ┆ … ┆ 35      ┆ 36     ┆ 9     ┆ 9    │
│ 128                 ┆ 176 ┆ 5     ┆ 72   ┆ … ┆ 77      ┆ 84     ┆ 11    ┆ 7    │
│ 256                 ┆ 134 ┆ 5     ┆ 37   ┆ … ┆ 35      ┆ 35     ┆ 8     ┆ 11   │
│ 512                 ┆ 118 ┆ 5     ┆ 36   ┆ … ┆ 34      ┆ 35     ┆ 9     ┆ 11   │
│ 1024                ┆ 127 ┆ 9     ┆ 41   ┆ … ┆ 39      ┆ 45     ┆ 6     ┆ 10   │
└─────────────────────┴─────┴───────┴──────┴───┴─────────┴────────┴───────┴──────┘

### Best Test Recall@20

In [80]:
(
    experiment_summary[["embedding_dimension", "l2_regularization", "best:epoch/test_recall@20"]].pivot(
        values=["best:epoch/test_recall@20"],
        index="embedding_dimension",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("embedding_dimension")
    .style.background_gradient(cmap="RdYlGn", axis=None)
)

### Best Test NDCG@20

In [81]:
(
    experiment_summary[["embedding_dimension", "l2_regularization", "best:epoch/test_ndcg@20"]].pivot(
        values=["best:epoch/test_ndcg@20"],
        index="embedding_dimension",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("embedding_dimension")
    .style.background_gradient(cmap="RdYlGn", axis=None)
)

## L1 Regularization Impact

In [82]:
experiment_summary = experiment_runs.filter(
    # pl.col("shuffle") == False,
    # pl.col("embedding_dimension") == 64,
    # pl.col("l1_regularization") == 0.0,
    # pl.col("l2_regularization") == 0.0,
    # pl.col("embedding_dropout_rate") == 0.0
).group_by( # group over random_seed runs
    "shuffle", "embedding_dimension", "l2_regularization", "l1_regularization"
).agg(
    pl.col("run_id").count().alias("num_runs"),
    pl.col("best:epoch/epoch").mean(),
    pl.col("best:epoch/test_recall@10").mean(),
    pl.col("best:epoch/test_ndcg@10").mean(),
    pl.col("best:epoch/test_recall@20").mean(),
    pl.col("best:epoch/test_ndcg@20").mean(),
).group_by( # group over unrelevant parameters, e.g., regularization
    "l1_regularization", "embedding_dimension"
).agg(
    pl.col("num_runs").sum(),
    pl.col("best:epoch/epoch").mean(),
    pl.col("best:epoch/test_recall@10").max(),
    pl.col("best:epoch/test_ndcg@10").max(),
    pl.col("best:epoch/test_recall@20").max(),
    pl.col("best:epoch/test_ndcg@20").max(),
).sort("l1_regularization", "embedding_dimension")

### Run Counts

In [83]:
experiment_summary[["embedding_dimension", "l1_regularization", "num_runs"]].pivot(
    values=["num_runs"],
    index="embedding_dimension",
    columns="l1_regularization"
)

/tmp/ipykernel_3771275/219270696.py:1: DeprecationWarning: the argument `columns` for `DataFrame.pivot` is deprecated. It was renamed to `on` in version 1.0.0.
  experiment_summary[["embedding_dimension", "l1_regularization", "num_runs"]].pivot(

shape: (10, 11)
┌─────────────────────┬─────┬───────┬──────┬───┬─────────┬────────┬───────┬──────┐
│ embedding_dimension ┆ 0.0 ┆ 1e-10 ┆ 1e-9 ┆ … ┆ 0.00001 ┆ 0.0001 ┆ 0.001 ┆ 0.01 │
│ ---                 ┆ --- ┆ ---   ┆ ---  ┆   ┆ ---     ┆ ---    ┆ ---   ┆ ---  │
│ i64                 ┆ u32 ┆ u32   ┆ u32  ┆   ┆ u32     ┆ u32    ┆ u32   ┆ u32  │
╞═════════════════════╪═════╪═══════╪══════╪═══╪═════════╪════════╪═══════╪══════╡
│ 2                   ┆ 130 ┆ 6     ┆ 33   ┆ … ┆ 21      ┆ 18     ┆ 7     ┆ 14   │
│ 4                   ┆ 136 ┆ 8     ┆ 21   ┆ … ┆ 20      ┆ 18     ┆ 8     ┆ 9    │
│ 8                   ┆ 136 ┆ 6     ┆ 25   ┆ … ┆ 22      ┆ 20     ┆ 8     ┆ 6    │
│ 16                  ┆ 137 ┆ 6     ┆ 25   ┆ … ┆ 18      ┆ 24     ┆ 7     ┆ 7    │
│ 32                  ┆ 120 ┆ 8     ┆ 21   ┆ … ┆ 25      ┆ 21     ┆ 7     ┆ 9    │
│ 64                  ┆ 122 ┆ 7     ┆ 44   ┆ … ┆ 34      ┆ 36     ┆ 10    ┆ 5    │
│ 128                 ┆ 183 ┆ 6     ┆ 72   ┆ … ┆ 75      ┆ 79     ┆ 11    ┆ 7    │
│ 256                 ┆ 129 ┆ 7     ┆ 42   ┆ … ┆ 39      ┆ 35     ┆ 12    ┆ 8    │
│ 512                 ┆ 120 ┆ 8     ┆ 39   ┆ … ┆ 32      ┆ 37     ┆ 9     ┆ 9    │
│ 1024                ┆ 126 ┆ 8     ┆ 48   ┆ … ┆ 39      ┆ 34     ┆ 8     ┆ 8    │
└─────────────────────┴─────┴───────┴──────┴───┴─────────┴────────┴───────┴──────┘

### Best Test Recall@20

In [84]:
(
    experiment_summary[["embedding_dimension", "l1_regularization", "best:epoch/test_recall@20"]].pivot(
        values=["best:epoch/test_recall@20"],
        index="embedding_dimension",
        on="l1_regularization"
    )
    .to_pandas()
    .set_index("embedding_dimension")
    .style.background_gradient(cmap="RdYlGn", axis=None)
)

### Best Test NDCG@20

In [85]:
(
    experiment_summary[["embedding_dimension", "l1_regularization", "best:epoch/test_ndcg@20"]].pivot(
        values=["best:epoch/test_ndcg@20"],
        index="embedding_dimension",
        on="l1_regularization"
    )
    .to_pandas()
    .set_index("embedding_dimension")
    .style.background_gradient(cmap="RdYlGn", axis=None)
)

## Shuffle Impact

In [112]:
experiment_summary = experiment_runs.filter(
    # pl.col("shuffle") == False,
    # pl.col("embedding_dimension") == 64,
    pl.col("l1_regularization") == 0.0,
    # pl.col("l2_regularization") == 0.0,
    pl.col("embedding_dropout_rate") == 0.0
).group_by( # group over random_seed runs
    "shuffle", "embedding_dimension", "l2_regularization", "l1_regularization"
).agg(
    pl.col("run_id").count().alias("num_runs"),
    pl.col("best:epoch/epoch").mean(),
    pl.col("best:epoch/test_recall@10").mean(),
    pl.col("best:epoch/test_ndcg@10").mean(),
    pl.col("best:epoch/train_recall@20").max(),
    pl.col("best:epoch/train_ndcg@20").max(),
    pl.col("best:epoch/test_recall@20").mean(),
    pl.col("best:epoch/test_ndcg@20").mean(),
).group_by( # group over unrelevant parameters, e.g., regularization
    "shuffle", "embedding_dimension"
).agg(
    pl.col("num_runs").sum(),
    pl.col("best:epoch/epoch").mean(),
    pl.col("best:epoch/test_recall@10").max(),
    pl.col("best:epoch/test_ndcg@10").max(),
    pl.col("best:epoch/train_recall@20").max(),
    pl.col("best:epoch/train_ndcg@20").max(),
    pl.col("best:epoch/test_recall@20").max(),
    pl.col("best:epoch/test_ndcg@20").max(),
).sort("shuffle", "embedding_dimension")

### Run Counts

In [113]:
experiment_summary[["embedding_dimension", "shuffle", "num_runs"]].pivot(
    values=["num_runs"],
    index="embedding_dimension",
    columns="shuffle"
)

/tmp/ipykernel_3771275/3242880112.py:1: DeprecationWarning: the argument `columns` for `DataFrame.pivot` is deprecated. It was renamed to `on` in version 1.0.0.
  experiment_summary[["embedding_dimension", "shuffle", "num_runs"]].pivot(

shape: (10, 3)
┌─────────────────────┬───────┬──────┐
│ embedding_dimension ┆ false ┆ true │
│ ---                 ┆ ---   ┆ ---  │
│ i64                 ┆ u32   ┆ u32  │
╞═════════════════════╪═══════╪══════╡
│ 2                   ┆ 48    ┆ 44   │
│ 4                   ┆ 48    ┆ 51   │
│ 8                   ┆ 51    ┆ 49   │
│ 16                  ┆ 47    ┆ 55   │
│ 32                  ┆ 53    ┆ 49   │
│ 64                  ┆ 49    ┆ 55   │
│ 128                 ┆ 77    ┆ 88   │
│ 256                 ┆ 55    ┆ 56   │
│ 512                 ┆ 47    ┆ 55   │
│ 1024                ┆ 50    ┆ 54   │
└─────────────────────┴───────┴──────┘

### Best Test Recall@20

In [114]:
train_recall = (
        experiment_summary[["embedding_dimension", "shuffle", "best:epoch/train_recall@20"]].pivot(
        values=["best:epoch/train_recall@20"],
        index="embedding_dimension",
        on="shuffle"
    )
    .to_pandas()
    .set_index("embedding_dimension")
)

test_recall = (
    experiment_summary[["embedding_dimension", "shuffle", "best:epoch/test_recall@20"]].pivot(
        values=["best:epoch/test_recall@20"],
        index="embedding_dimension",
        on="shuffle"
    )
    .to_pandas()
    .set_index("embedding_dimension")
)

display(Markdown("#### Train Recall@20"))
display(train_recall.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Test Recall@20"))
display(test_recall.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Train-Test Recall@20 Difference"))
display((train_recall - test_recall).style.background_gradient(cmap="RdYlGn_r", axis=None))

#### Train Recall@20

#### Test Recall@20

#### Train-Test Recall@20 Difference

### Best Test NDCG@20

In [115]:
train_ndcg = (
    experiment_summary[["embedding_dimension", "shuffle", "best:epoch/train_ndcg@20"]].pivot(
        values=["best:epoch/train_ndcg@20"],
        index="embedding_dimension",
        on="shuffle"
    )
    .to_pandas()
    .set_index("embedding_dimension")
)

test_ndcg = (
    experiment_summary[["embedding_dimension", "shuffle", "best:epoch/test_ndcg@20"]].pivot(
        values=["best:epoch/test_ndcg@20"],
        index="embedding_dimension",
        on="shuffle"
    )
    .to_pandas()
    .set_index("embedding_dimension")
)

display(Markdown("#### Train NDCG@20"))
display(train_ndcg.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Test NDCG@20"))
display(test_ndcg.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Train-Test NDCG@20 Difference"))
display((train_ndcg - test_ndcg).style.background_gradient(cmap="RdYlGn_r", axis=None))

#### Train NDCG@20

#### Test NDCG@20

#### Train-Test NDCG@20 Difference

# Parameter Comparison Deep Dive
Here we select only 2 free variables and fixed the rest to see what effect these two variable had

## L2 Regularization, Shuffle = False, L1 = 0.0, Dropout = 0.0

In [3]:
experiment_summary = experiment_runs.filter(
    pl.col("shuffle") == False,
    pl.col("l1_regularization") == 0.0,
    pl.col("embedding_dropout_rate") == 0.0
).group_by(
    "embedding_dimension", "l2_regularization"
).agg(
    pl.col("run_id").count().alias("num_runs"),
    pl.col("best:epoch/epoch").mean(),
    pl.col("best:epoch/test_recall@10").mean(),
    pl.col("best:epoch/test_ndcg@10").mean(),
    pl.col("best:epoch/train_recall@20").mean(),
    pl.col("best:epoch/train_ndcg@20").mean(),
    pl.col("best:epoch/test_recall@20").mean(),
    pl.col("best:epoch/test_ndcg@20").mean(),
).sort("embedding_dimension", "l2_regularization")

### Run Counts

In [4]:
experiment_summary[["embedding_dimension", "l2_regularization", "num_runs"]].pivot(
    values=["num_runs"],
    index="embedding_dimension",
    columns="l2_regularization"
)

/tmp/ipykernel_1783924/2842099446.py:1: DeprecationWarning: the argument `columns` for `DataFrame.pivot` is deprecated. It was renamed to `on` in version 1.0.0.
  experiment_summary[["embedding_dimension", "l2_regularization", "num_runs"]].pivot(

shape: (10, 11)
┌─────────────────────┬─────┬───────┬──────┬───┬─────────┬────────┬───────┬──────┐
│ embedding_dimension ┆ 0.0 ┆ 1e-10 ┆ 1e-9 ┆ … ┆ 0.00001 ┆ 0.0001 ┆ 0.001 ┆ 0.01 │
│ ---                 ┆ --- ┆ ---   ┆ ---  ┆   ┆ ---     ┆ ---    ┆ ---   ┆ ---  │
│ i64                 ┆ u32 ┆ u32   ┆ u32  ┆   ┆ u32     ┆ u32    ┆ u32   ┆ u32  │
╞═════════════════════╪═════╪═══════╪══════╪═══╪═════════╪════════╪═══════╪══════╡
│ 2                   ┆ 6   ┆ 4     ┆ 4    ┆ … ┆ 6       ┆ 4      ┆ 5     ┆ 6    │
│ 4                   ┆ 9   ┆ 2     ┆ 4    ┆ … ┆ 4       ┆ 6      ┆ 4     ┆ 7    │
│ 8                   ┆ 9   ┆ 9     ┆ 4    ┆ … ┆ 3       ┆ 4      ┆ 5     ┆ 3    │
│ 16                  ┆ 8   ┆ 2     ┆ 2    ┆ … ┆ 3       ┆ 9      ┆ 4     ┆ 4    │
│ 32                  ┆ 4   ┆ 3     ┆ 3    ┆ … ┆ 4       ┆ 6      ┆ 9     ┆ 8    │
│ 64                  ┆ 6   ┆ 3     ┆ 4    ┆ … ┆ 6       ┆ 5      ┆ 5     ┆ 2    │
│ 128                 ┆ 15  ┆ 2     ┆ 7    ┆ … ┆ 8       ┆ 6      ┆ 7     ┆ 3    │
│ 256                 ┆ 11  ┆ 3     ┆ 5    ┆ … ┆ 6       ┆ 4      ┆ 5     ┆ 6    │
│ 512                 ┆ 7   ┆ 2     ┆ 4    ┆ … ┆ 5       ┆ 7      ┆ 4     ┆ 4    │
│ 1024                ┆ 8   ┆ 5     ┆ 3    ┆ … ┆ 7       ┆ 9      ┆ 3     ┆ 5    │
└─────────────────────┴─────┴───────┴──────┴───┴─────────┴────────┴───────┴──────┘

### Best Epoch

In [5]:
(
    experiment_summary[["embedding_dimension", "l2_regularization", "best:epoch/epoch"]].pivot(
        values=["best:epoch/epoch"],
        index="embedding_dimension",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("embedding_dimension")
    .style.background_gradient(cmap="Blues", axis=None)
    .format("{:.2f}")
)

### Best Recall@20

In [6]:
train_recall = (
        experiment_summary[["embedding_dimension", "l2_regularization", "best:epoch/train_recall@20"]].pivot(
        values=["best:epoch/train_recall@20"],
        index="embedding_dimension",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("embedding_dimension")
)

test_recall = (
    experiment_summary[["embedding_dimension", "l2_regularization", "best:epoch/test_recall@20"]].pivot(
        values=["best:epoch/test_recall@20"],
        index="embedding_dimension",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("embedding_dimension")
)

display(Markdown("#### Train Recall@20"))
display(train_recall.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Test Recall@20"))
display(test_recall.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Train-Test Recall@20 Difference"))
display((train_recall - test_recall).style.background_gradient(cmap="RdYlGn_r", axis=None))

#### Train Recall@20

#### Test Recall@20

#### Train-Test Recall@20 Difference

### Best Test NDCG@20

In [7]:
train_ndcg = (
    experiment_summary[["embedding_dimension", "l2_regularization", "best:epoch/train_ndcg@20"]].pivot(
        values=["best:epoch/train_ndcg@20"],
        index="embedding_dimension",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("embedding_dimension")
)

test_ndcg = (
    experiment_summary[["embedding_dimension", "l2_regularization", "best:epoch/test_ndcg@20"]].pivot(
        values=["best:epoch/test_ndcg@20"],
        index="embedding_dimension",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("embedding_dimension")
)

display(Markdown("#### Train NDCG@20"))
display(train_ndcg.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Test NDCG@20"))
display(test_ndcg.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Train-Test NDCG@20 Difference"))
display((train_ndcg - test_ndcg).style.background_gradient(cmap="RdYlGn_r", axis=None))

#### Train NDCG@20

#### Test NDCG@20

#### Train-Test NDCG@20 Difference

## L2 Regularization, Shuffle = True, L1 = 0.0, Dropout = 0.0

In [90]:
experiment_summary = experiment_runs.filter(
    pl.col("shuffle") == True,
    pl.col("l1_regularization") == 0.0,
    pl.col("embedding_dropout_rate") == 0.0
).group_by(
    "embedding_dimension", "l2_regularization"
).agg(
    pl.col("run_id").count().alias("num_runs"),
    pl.col("best:epoch/epoch").mean(),
    pl.col("best:epoch/test_recall@10").mean(),
    pl.col("best:epoch/test_ndcg@10").mean(),
    pl.col("best:epoch/train_recall@20").mean(),
    pl.col("best:epoch/train_ndcg@20").mean(),
    pl.col("best:epoch/test_recall@20").mean(),
    pl.col("best:epoch/test_ndcg@20").mean(),
).sort("embedding_dimension", "l2_regularization")

In [92]:
experiment_summary["num_runs"].sum()

556

### Run Counts

In [93]:
experiment_summary[["embedding_dimension", "l2_regularization", "num_runs"]].pivot(
    values=["num_runs"],
    index="embedding_dimension",
    columns="l2_regularization"
)

/tmp/ipykernel_3771275/2842099446.py:1: DeprecationWarning: the argument `columns` for `DataFrame.pivot` is deprecated. It was renamed to `on` in version 1.0.0.
  experiment_summary[["embedding_dimension", "l2_regularization", "num_runs"]].pivot(

shape: (10, 11)
┌─────────────────────┬─────┬───────┬──────┬───┬─────────┬────────┬───────┬──────┐
│ embedding_dimension ┆ 0.0 ┆ 1e-10 ┆ 1e-9 ┆ … ┆ 0.00001 ┆ 0.0001 ┆ 0.001 ┆ 0.01 │
│ ---                 ┆ --- ┆ ---   ┆ ---  ┆   ┆ ---     ┆ ---    ┆ ---   ┆ ---  │
│ i64                 ┆ u32 ┆ u32   ┆ u32  ┆   ┆ u32     ┆ u32    ┆ u32   ┆ u32  │
╞═════════════════════╪═════╪═══════╪══════╪═══╪═════════╪════════╪═══════╪══════╡
│ 2                   ┆ 7   ┆ 3     ┆ 3    ┆ … ┆ 5       ┆ 3      ┆ 7     ┆ 4    │
│ 4                   ┆ 7   ┆ 3     ┆ 5    ┆ … ┆ 5       ┆ 8      ┆ 5     ┆ 3    │
│ 8                   ┆ 9   ┆ 4     ┆ 2    ┆ … ┆ 5       ┆ 5      ┆ 4     ┆ 7    │
│ 16                  ┆ 8   ┆ 3     ┆ 2    ┆ … ┆ 9       ┆ 4      ┆ 5     ┆ 6    │
│ 32                  ┆ 11  ┆ 2     ┆ 2    ┆ … ┆ 3       ┆ 3      ┆ 3     ┆ 7    │
│ 64                  ┆ 7   ┆ 5     ┆ 5    ┆ … ┆ 4       ┆ 7      ┆ 4     ┆ 7    │
│ 128                 ┆ 12  ┆ 3     ┆ 9    ┆ … ┆ 8       ┆ 10     ┆ 4     ┆ 4    │
│ 256                 ┆ 10  ┆ 2     ┆ 4    ┆ … ┆ 3       ┆ 5      ┆ 3     ┆ 5    │
│ 512                 ┆ 5   ┆ 3     ┆ 6    ┆ … ┆ 4       ┆ 4      ┆ 5     ┆ 7    │
│ 1024                ┆ 6   ┆ 4     ┆ 6    ┆ … ┆ 6       ┆ 9      ┆ 3     ┆ 5    │
└─────────────────────┴─────┴───────┴──────┴───┴─────────┴────────┴───────┴──────┘

### Best Epoch

In [94]:
(
    experiment_summary[["embedding_dimension", "l2_regularization", "best:epoch/epoch"]].pivot(
        values=["best:epoch/epoch"],
        index="embedding_dimension",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("embedding_dimension")
    .style.background_gradient(cmap="Blues", axis=None)
    .format("{:.2f}")
)

### Best Recall@20

In [95]:
train_recall = (
        experiment_summary[["embedding_dimension", "l2_regularization", "best:epoch/train_recall@20"]].pivot(
        values=["best:epoch/train_recall@20"],
        index="embedding_dimension",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("embedding_dimension")
)

test_recall = (
    experiment_summary[["embedding_dimension", "l2_regularization", "best:epoch/test_recall@20"]].pivot(
        values=["best:epoch/test_recall@20"],
        index="embedding_dimension",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("embedding_dimension")
)

display(Markdown("#### Train Recall@20"))
display(train_recall.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Test Recall@20"))
display(test_recall.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Train-Test Recall@20 Difference"))
display((train_recall - test_recall).style.background_gradient(cmap="RdYlGn_r", axis=None))

#### Train Recall@20

#### Test Recall@20

#### Train-Test Recall@20 Difference

### Best Test NDCG@20

In [9]:
train_ndcg = (
    experiment_summary[["embedding_dimension", "l2_regularization", "best:epoch/train_ndcg@20"]].pivot(
        values=["best:epoch/train_ndcg@20"],
        index="embedding_dimension",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("embedding_dimension")
)

test_ndcg = (
    experiment_summary[["embedding_dimension", "l2_regularization", "best:epoch/test_ndcg@20"]].pivot(
        values=["best:epoch/test_ndcg@20"],
        index="embedding_dimension",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("embedding_dimension")
)

display(Markdown("#### Train NDCG@20"))
display(train_ndcg.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Test NDCG@20"))
display(test_ndcg.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Train-Test NDCG@20 Difference"))
display((train_ndcg - test_ndcg).style.background_gradient(cmap="RdYlGn_r", axis=None))

#### Train NDCG@20

#### Test NDCG@20

#### Train-Test NDCG@20 Difference

## L1 Regularizatio, Shuffle = False, L2 = 0.0, Dropout = 0.0

In [10]:
experiment_summary = experiment_runs.filter(
    pl.col("shuffle") == False,
    pl.col("l2_regularization") == 0.0,
    pl.col("embedding_dropout_rate") == 0.0
).group_by(
    "embedding_dimension", "l1_regularization"
).agg(
    pl.col("run_id").count().alias("num_runs"),
    pl.col("best:epoch/epoch").mean(),
    pl.col("best:epoch/test_recall@10").mean(),
    pl.col("best:epoch/test_ndcg@10").mean(),
    pl.col("best:epoch/train_recall@20").mean(),
    pl.col("best:epoch/train_ndcg@20").mean(),
    pl.col("best:epoch/test_recall@20").mean(),
    pl.col("best:epoch/test_ndcg@20").mean(),
).sort("embedding_dimension", "l1_regularization")

### Run Counts

In [11]:
experiment_summary[["embedding_dimension", "l1_regularization", "num_runs"]].pivot(
    values=["num_runs"],
    index="embedding_dimension",
    columns="l1_regularization"
)

/tmp/ipykernel_3771275/219270696.py:1: DeprecationWarning: the argument `columns` for `DataFrame.pivot` is deprecated. It was renamed to `on` in version 1.0.0.
  experiment_summary[["embedding_dimension", "l1_regularization", "num_runs"]].pivot(

shape: (10, 11)
┌─────────────────────┬─────┬───────┬──────┬───┬─────────┬────────┬───────┬──────┐
│ embedding_dimension ┆ 0.0 ┆ 1e-10 ┆ 1e-9 ┆ … ┆ 0.00001 ┆ 0.0001 ┆ 0.001 ┆ 0.01 │
│ ---                 ┆ --- ┆ ---   ┆ ---  ┆   ┆ ---     ┆ ---    ┆ ---   ┆ ---  │
│ i64                 ┆ u32 ┆ u32   ┆ u32  ┆   ┆ u32     ┆ u32    ┆ u32   ┆ u32  │
╞═════════════════════╪═════╪═══════╪══════╪═══╪═════════╪════════╪═══════╪══════╡
│ 2                   ┆ 6   ┆ 3     ┆ 4    ┆ … ┆ 6       ┆ 3      ┆ 4     ┆ 7    │
│ 4                   ┆ 9   ┆ 3     ┆ 3    ┆ … ┆ 4       ┆ 3      ┆ 5     ┆ 6    │
│ 8                   ┆ 9   ┆ 3     ┆ 6    ┆ … ┆ 7       ┆ 3      ┆ 5     ┆ 3    │
│ 16                  ┆ 8   ┆ 2     ┆ 5    ┆ … ┆ 4       ┆ 6      ┆ 4     ┆ 4    │
│ 32                  ┆ 4   ┆ 5     ┆ 5    ┆ … ┆ 5       ┆ 5      ┆ 3     ┆ 4    │
│ 64                  ┆ 6   ┆ 3     ┆ 4    ┆ … ┆ 3       ┆ 5      ┆ 4     ┆ 2    │
│ 128                 ┆ 15  ┆ 3     ┆ 10   ┆ … ┆ 8       ┆ 5      ┆ 4     ┆ 3    │
│ 256                 ┆ 11  ┆ 5     ┆ 3    ┆ … ┆ 6       ┆ 3      ┆ 7     ┆ 3    │
│ 512                 ┆ 7   ┆ 2     ┆ 4    ┆ … ┆ 4       ┆ 4      ┆ 4     ┆ 5    │
│ 1024                ┆ 8   ┆ 4     ┆ 8    ┆ … ┆ 5       ┆ 3      ┆ 5     ┆ 3    │
└─────────────────────┴─────┴───────┴──────┴───┴─────────┴────────┴───────┴──────┘

### Best Epoch

In [12]:
(
    experiment_summary[["embedding_dimension", "l1_regularization", "best:epoch/epoch"]].pivot(
        values=["best:epoch/epoch"],
        index="embedding_dimension",
        on="l1_regularization"
    )
    .to_pandas()
    .set_index("embedding_dimension")
    .style.background_gradient(cmap="Blues", axis=None)
    .format("{:.2f}")
)

### Best Recall@20

In [13]:
train_recall = (
        experiment_summary[["embedding_dimension", "l1_regularization", "best:epoch/train_recall@20"]].pivot(
        values=["best:epoch/train_recall@20"],
        index="embedding_dimension",
        on="l1_regularization"
    )
    .to_pandas()
    .set_index("embedding_dimension")
)

test_recall = (
    experiment_summary[["embedding_dimension", "l1_regularization", "best:epoch/test_recall@20"]].pivot(
        values=["best:epoch/test_recall@20"],
        index="embedding_dimension",
        on="l1_regularization"
    )
    .to_pandas()
    .set_index("embedding_dimension")
)

display(Markdown("#### Train Recall@20"))
display(train_recall.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Test Recall@20"))
display(test_recall.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Train-Test Recall@20 Difference"))
display((train_recall - test_recall).style.background_gradient(cmap="RdYlGn_r", axis=None))

#### Train Recall@20

#### Test Recall@20

#### Train-Test Recall@20 Difference

### Best NDCG@20

In [14]:
train_ndcg = (
    experiment_summary[["embedding_dimension", "l1_regularization", "best:epoch/train_ndcg@20"]].pivot(
        values=["best:epoch/train_ndcg@20"],
        index="embedding_dimension",
        on="l1_regularization"
    )
    .to_pandas()
    .set_index("embedding_dimension")
)

test_ndcg = (
    experiment_summary[["embedding_dimension", "l1_regularization", "best:epoch/test_ndcg@20"]].pivot(
        values=["best:epoch/test_ndcg@20"],
        index="embedding_dimension",
        on="l1_regularization"
    )
    .to_pandas()
    .set_index("embedding_dimension")
)

display(Markdown("#### Train NDCG@20"))
display(train_ndcg.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Test NDCG@20"))
display(test_ndcg.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Train-Test NDCG@20 Difference"))
display((train_ndcg - test_ndcg).style.background_gradient(cmap="RdYlGn_r", axis=None))

#### Train NDCG@20

#### Test NDCG@20

#### Train-Test NDCG@20 Difference

## L1 Regularization, Shuffle = True, L2 = 0.0, Dropout = 0.0

In [15]:
experiment_summary = experiment_runs.filter(
    pl.col("shuffle") == True,
    pl.col("l2_regularization") == 0.0,
    pl.col("embedding_dropout_rate") == 0.0
).group_by(
    "embedding_dimension", "l1_regularization"
).agg(
    pl.col("run_id").count().alias("num_runs"),
    pl.col("best:epoch/epoch").mean(),
    pl.col("best:epoch/test_recall@10").mean(),
    pl.col("best:epoch/test_ndcg@10").mean(),
    pl.col("best:epoch/train_recall@20").mean(),
    pl.col("best:epoch/train_ndcg@20").mean(),
    pl.col("best:epoch/test_recall@20").mean(),
    pl.col("best:epoch/test_ndcg@20").mean(),
).sort("embedding_dimension", "l1_regularization")

### Run Counts

In [16]:
experiment_summary[["embedding_dimension", "l1_regularization", "num_runs"]].pivot(
    values=["num_runs"],
    index="embedding_dimension",
    columns="l1_regularization"
)

/tmp/ipykernel_3771275/219270696.py:1: DeprecationWarning: the argument `columns` for `DataFrame.pivot` is deprecated. It was renamed to `on` in version 1.0.0.
  experiment_summary[["embedding_dimension", "l1_regularization", "num_runs"]].pivot(

shape: (10, 11)
┌─────────────────────┬─────┬───────┬──────┬───┬─────────┬────────┬───────┬──────┐
│ embedding_dimension ┆ 0.0 ┆ 1e-10 ┆ 1e-9 ┆ … ┆ 0.00001 ┆ 0.0001 ┆ 0.001 ┆ 0.01 │
│ ---                 ┆ --- ┆ ---   ┆ ---  ┆   ┆ ---     ┆ ---    ┆ ---   ┆ ---  │
│ i64                 ┆ u32 ┆ u32   ┆ u32  ┆   ┆ u32     ┆ u32    ┆ u32   ┆ u32  │
╞═════════════════════╪═════╪═══════╪══════╪═══╪═════════╪════════╪═══════╪══════╡
│ 2                   ┆ 7   ┆ 3     ┆ 8    ┆ … ┆ 3       ┆ 3      ┆ 3     ┆ 7    │
│ 4                   ┆ 7   ┆ 5     ┆ 4    ┆ … ┆ 3       ┆ 3      ┆ 3     ┆ 3    │
│ 8                   ┆ 9   ┆ 3     ┆ 7    ┆ … ┆ 3       ┆ 3      ┆ 3     ┆ 3    │
│ 16                  ┆ 8   ┆ 4     ┆ 6    ┆ … ┆ 2       ┆ 5      ┆ 3     ┆ 3    │
│ 32                  ┆ 11  ┆ 3     ┆ 4    ┆ … ┆ 4       ┆ 4      ┆ 4     ┆ 5    │
│ 64                  ┆ 7   ┆ 4     ┆ 5    ┆ … ┆ 5       ┆ 6      ┆ 6     ┆ 3    │
│ 128                 ┆ 12  ┆ 3     ┆ 10   ┆ … ┆ 15      ┆ 7      ┆ 7     ┆ 4    │
│ 256                 ┆ 10  ┆ 2     ┆ 7    ┆ … ┆ 7       ┆ 5      ┆ 5     ┆ 5    │
│ 512                 ┆ 5   ┆ 6     ┆ 5    ┆ … ┆ 4       ┆ 8      ┆ 5     ┆ 4    │
│ 1024                ┆ 6   ┆ 4     ┆ 7    ┆ … ┆ 4       ┆ 5      ┆ 3     ┆ 5    │
└─────────────────────┴─────┴───────┴──────┴───┴─────────┴────────┴───────┴──────┘

### Best Epoch

In [17]:
(
    experiment_summary[["embedding_dimension", "l1_regularization", "best:epoch/epoch"]].pivot(
        values=["best:epoch/epoch"],
        index="embedding_dimension",
        on="l1_regularization"
    )
    .to_pandas()
    .set_index("embedding_dimension")
    .style.background_gradient(cmap="Blues", axis=None)
    .format("{:.2f}")
)

### Best Recall@20

In [18]:
train_recall = (
        experiment_summary[["embedding_dimension", "l1_regularization", "best:epoch/train_recall@20"]].pivot(
        values=["best:epoch/train_recall@20"],
        index="embedding_dimension",
        on="l1_regularization"
    )
    .to_pandas()
    .set_index("embedding_dimension")
)

test_recall = (
    experiment_summary[["embedding_dimension", "l1_regularization", "best:epoch/test_recall@20"]].pivot(
        values=["best:epoch/test_recall@20"],
        index="embedding_dimension",
        on="l1_regularization"
    )
    .to_pandas()
    .set_index("embedding_dimension")
)

display(Markdown("#### Train Recall@20"))
display(train_recall.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Test Recall@20"))
display(test_recall.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Train-Test Recall@20 Difference"))
display((train_recall - test_recall).style.background_gradient(cmap="RdYlGn_r", axis=None))

#### Train Recall@20

#### Test Recall@20

#### Train-Test Recall@20 Difference

### Best NDCG@20

In [19]:
train_ndcg = (
    experiment_summary[["embedding_dimension", "l1_regularization", "best:epoch/train_ndcg@20"]].pivot(
        values=["best:epoch/train_ndcg@20"],
        index="embedding_dimension",
        on="l1_regularization"
    )
    .to_pandas()
    .set_index("embedding_dimension")
)

test_ndcg = (
    experiment_summary[["embedding_dimension", "l1_regularization", "best:epoch/test_ndcg@20"]].pivot(
        values=["best:epoch/test_ndcg@20"],
        index="embedding_dimension",
        on="l1_regularization"
    )
    .to_pandas()
    .set_index("embedding_dimension")
)

display(Markdown("#### Train NDCG@20"))
display(train_ndcg.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Test NDCG@20"))
display(test_ndcg.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Train-Test NDCG@20 Difference"))
display((train_ndcg - test_ndcg).style.background_gradient(cmap="RdYlGn_r", axis=None))

#### Train NDCG@20

#### Test NDCG@20

#### Train-Test NDCG@20 Difference

## ElasticNet, D=128, Shuffle = False
We want to further deep dive what will happen if we use both L1 and L2 (or better know as ElasticNet) at the same time on Matrix Factorization.

In [20]:
experiment_summary = experiment_runs.filter(
    pl.col("shuffle") == False,
    pl.col("embedding_dimension") == 128,
    pl.col("l1_regularization") != 1e-10, pl.col("l1_regularization") <= 1e-4,
    pl.col("l2_regularization") != 1e-10, pl.col("l2_regularization") <= 1e-4,
    pl.col("embedding_dropout_rate") == 0.0
).group_by(
    "l1_regularization", "l2_regularization"
).agg(
    pl.col("run_id").count().alias("num_runs"),
    pl.col("best:epoch/epoch").mean(),
    pl.col("best:epoch/test_recall@10").mean(),
    pl.col("best:epoch/test_ndcg@10").mean(),
    pl.col("best:epoch/train_recall@20").mean(),
    pl.col("best:epoch/train_ndcg@20").mean(),
    pl.col("best:epoch/test_recall@20").mean(),
    pl.col("best:epoch/test_ndcg@20").mean(),
).sort(
    "l1_regularization", "l2_regularization"
).with_columns(
    pl.col("l1_regularization").cast(pl.Utf8),
    pl.col("l2_regularization").cast(pl.Utf8)
)

### Run Counts

In [21]:
experiment_summary[["l1_regularization", "l2_regularization", "num_runs"]].pivot(
    values=["num_runs"],
    index="l1_regularization",
    columns="l2_regularization"
)

/tmp/ipykernel_3771275/1305047977.py:1: DeprecationWarning: the argument `columns` for `DataFrame.pivot` is deprecated. It was renamed to `on` in version 1.0.0.
  experiment_summary[["l1_regularization", "l2_regularization", "num_runs"]].pivot(

shape: (7, 8)
┌───────────────────┬─────┬──────┬──────┬──────┬──────┬─────────┬────────┐
│ l1_regularization ┆ 0.0 ┆ 1e-9 ┆ 1e-8 ┆ 1e-7 ┆ 1e-6 ┆ 0.00001 ┆ 0.0001 │
│ ---               ┆ --- ┆ ---  ┆ ---  ┆ ---  ┆ ---  ┆ ---     ┆ ---    │
│ str               ┆ u32 ┆ u32  ┆ u32  ┆ u32  ┆ u32  ┆ u32     ┆ u32    │
╞═══════════════════╪═════╪══════╪══════╪══════╪══════╪═════════╪════════╡
│ 0.0               ┆ 15  ┆ 7    ┆ 8    ┆ 13   ┆ 8    ┆ 8       ┆ 6      │
│ 1e-9              ┆ 10  ┆ 3    ┆ 5    ┆ 3    ┆ 2    ┆ 4       ┆ 8      │
│ 1e-8              ┆ 5   ┆ 3    ┆ 2    ┆ 5    ┆ 6    ┆ 11      ┆ 3      │
│ 1e-7              ┆ 10  ┆ 3    ┆ 5    ┆ 7    ┆ 6    ┆ 7       ┆ 5      │
│ 1e-6              ┆ 6   ┆ 3    ┆ 2    ┆ 2    ┆ 6    ┆ 4       ┆ 2      │
│ 0.00001           ┆ 8   ┆ 2    ┆ 3    ┆ 6    ┆ 4    ┆ 3       ┆ 6      │
│ 0.0001            ┆ 5   ┆ 7    ┆ 4    ┆ 3    ┆ 7    ┆ 5       ┆ 7      │
└───────────────────┴─────┴──────┴──────┴──────┴──────┴─────────┴────────┘

### Best Epoch

In [22]:
(
    experiment_summary[["l1_regularization", "l2_regularization", "best:epoch/epoch"]].pivot(
        values=["best:epoch/epoch"],
        index="l1_regularization",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("l1_regularization")
    .style.background_gradient(cmap="Blues", axis=None)
    .format("{:.2f}")
)

### Best Recall@20

In [23]:
train_recall = (
        experiment_summary[["l1_regularization", "l2_regularization", "best:epoch/train_recall@20"]].pivot(
        values=["best:epoch/train_recall@20"],
        index="l1_regularization",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("l1_regularization")
)

test_recall = (
    experiment_summary[["l1_regularization", "l2_regularization", "best:epoch/test_recall@20"]].pivot(
        values=["best:epoch/test_recall@20"],
        index="l1_regularization",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("l1_regularization")
)

display(Markdown("#### Train Recall@20"))
display(train_recall.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Test Recall@20"))
display(test_recall.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Train-Test Recall@20 Difference"))
display((train_recall - test_recall).style.background_gradient(cmap="RdYlGn_r", axis=None))

#### Train Recall@20

#### Test Recall@20

#### Train-Test Recall@20 Difference

### Best NDCG@20

In [25]:
train_ndcg = (
    experiment_summary[["l1_regularization", "l2_regularization", "best:epoch/train_ndcg@20"]].pivot(
        values=["best:epoch/train_ndcg@20"],
        index="l1_regularization",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("l1_regularization")
)

test_ndcg = (
    experiment_summary[["l1_regularization", "l2_regularization", "best:epoch/test_ndcg@20"]].pivot(
        values=["best:epoch/test_ndcg@20"],
        index="l1_regularization",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("l1_regularization")
)

display(Markdown("#### Train NDCG@20"))
display(train_ndcg.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Test NDCG@20"))
display(test_ndcg.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Train-Test NDCG@20 Difference"))
display((train_ndcg - test_ndcg).style.background_gradient(cmap="RdYlGn_r", axis=None))

#### Train NDCG@20

#### Test NDCG@20

#### Train-Test NDCG@20 Difference

## ElasticNet, D=128, Shuffle = True
We want to further deep dive what will happen if we use both L1 and L2 (or better know as ElasticNet) at the same time on Matrix Factorization.

In [32]:
experiment_summary = experiment_runs.filter(
    pl.col("shuffle") == True,
    pl.col("embedding_dimension") == 128,
    pl.col("l1_regularization") != 1e-10, pl.col("l1_regularization") <= 1e-4,
    pl.col("l2_regularization") != 1e-10, pl.col("l2_regularization") <= 1e-4,
    pl.col("embedding_dropout_rate") == 0.0
).group_by(
    "l1_regularization", "l2_regularization"
).agg(
    pl.col("run_id").count().alias("num_runs"),
    pl.col("best:epoch/epoch").mean(),
    pl.col("best:epoch/test_recall@10").mean(),
    pl.col("best:epoch/test_ndcg@10").mean(),
    pl.col("best:epoch/train_recall@20").mean(),
    pl.col("best:epoch/train_ndcg@20").mean(),
    pl.col("best:epoch/test_recall@20").mean(),
    pl.col("best:epoch/test_ndcg@20").mean(),
).sort(
    "l1_regularization", "l2_regularization"
).with_columns(
    pl.col("l1_regularization").cast(pl.Utf8),
    pl.col("l2_regularization").cast(pl.Utf8)
)

### Run Counts

In [33]:
experiment_summary[["l1_regularization", "l2_regularization", "num_runs"]].pivot(
    values=["num_runs"],
    index="l1_regularization",
    columns="l2_regularization"
)

/tmp/ipykernel_3771275/1305047977.py:1: DeprecationWarning: the argument `columns` for `DataFrame.pivot` is deprecated. It was renamed to `on` in version 1.0.0.
  experiment_summary[["l1_regularization", "l2_regularization", "num_runs"]].pivot(

shape: (7, 8)
┌───────────────────┬─────┬──────┬──────┬──────┬──────┬─────────┬────────┐
│ l1_regularization ┆ 0.0 ┆ 1e-9 ┆ 1e-8 ┆ 1e-7 ┆ 1e-6 ┆ 0.00001 ┆ 0.0001 │
│ ---               ┆ --- ┆ ---  ┆ ---  ┆ ---  ┆ ---  ┆ ---     ┆ ---    │
│ str               ┆ u32 ┆ u32  ┆ u32  ┆ u32  ┆ u32  ┆ u32     ┆ u32    │
╞═══════════════════╪═════╪══════╪══════╪══════╪══════╪═════════╪════════╡
│ 0.0               ┆ 12  ┆ 9    ┆ 10   ┆ 16   ┆ 12   ┆ 8       ┆ 10     │
│ 1e-9              ┆ 10  ┆ 7    ┆ 4    ┆ 4    ┆ 2    ┆ 5       ┆ 5      │
│ 1e-8              ┆ 9   ┆ 9    ┆ 7    ┆ 3    ┆ 7    ┆ 3       ┆ 5      │
│ 1e-7              ┆ 10  ┆ 6    ┆ 7    ┆ 2    ┆ 6    ┆ 4       ┆ 6      │
│ 1e-6              ┆ 12  ┆ 2    ┆ 4    ┆ 6    ┆ 4    ┆ 6       ┆ 9      │
│ 0.00001           ┆ 15  ┆ 4    ┆ 2    ┆ 6    ┆ 3    ┆ 6       ┆ 7      │
│ 0.0001            ┆ 7   ┆ 7    ┆ 6    ┆ 5    ┆ 8    ┆ 3       ┆ 5      │
└───────────────────┴─────┴──────┴──────┴──────┴──────┴─────────┴────────┘

### Best Epoch

In [34]:
(
    experiment_summary[["l1_regularization", "l2_regularization", "best:epoch/epoch"]].pivot(
        values=["best:epoch/epoch"],
        index="l1_regularization",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("l1_regularization")
    .style.background_gradient(cmap="Blues", axis=None)
    .format("{:.2f}")
)

### Best Recall@20

In [35]:
train_recall = (
        experiment_summary[["l1_regularization", "l2_regularization", "best:epoch/train_recall@20"]].pivot(
        values=["best:epoch/train_recall@20"],
        index="l1_regularization",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("l1_regularization")
)

test_recall = (
    experiment_summary[["l1_regularization", "l2_regularization", "best:epoch/test_recall@20"]].pivot(
        values=["best:epoch/test_recall@20"],
        index="l1_regularization",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("l1_regularization")
)

display(Markdown("#### Train Recall@20"))
display(train_recall.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Test Recall@20"))
display(test_recall.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Train-Test Recall@20 Difference"))
display((train_recall - test_recall).style.background_gradient(cmap="RdYlGn_r", axis=None))

#### Train Recall@20

#### Test Recall@20

#### Train-Test Recall@20 Difference

### Best NDCG@20

In [36]:
train_ndcg = (
    experiment_summary[["l1_regularization", "l2_regularization", "best:epoch/train_ndcg@20"]].pivot(
        values=["best:epoch/train_ndcg@20"],
        index="l1_regularization",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("l1_regularization")
)

test_ndcg = (
    experiment_summary[["l1_regularization", "l2_regularization", "best:epoch/test_ndcg@20"]].pivot(
        values=["best:epoch/test_ndcg@20"],
        index="l1_regularization",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("l1_regularization")
)

display(Markdown("#### Train NDCG@20"))
display(train_ndcg.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Test NDCG@20"))
display(test_ndcg.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Train-Test NDCG@20 Difference"))
display((train_ndcg - test_ndcg).style.background_gradient(cmap="RdYlGn_r", axis=None))

#### Train NDCG@20

#### Test NDCG@20

#### Train-Test NDCG@20 Difference

## ElasticNet, D=512, Shuffle = False

In [60]:
experiment_summary = experiment_runs.filter(
    pl.col("shuffle") == False,
    pl.col("embedding_dimension") == 512,
    pl.col("l1_regularization") != 1e-10, pl.col("l1_regularization") <= 1e-4,
    pl.col("l2_regularization") != 1e-10, pl.col("l2_regularization") <= 1e-4,
    pl.col("embedding_dropout_rate") == 0.0
).group_by(
    "l1_regularization", "l2_regularization"
).agg(
    pl.col("run_id").count().alias("num_runs"),
    pl.col("best:epoch/epoch").mean(),
    pl.col("best:epoch/test_recall@10").mean(),
    pl.col("best:epoch/test_ndcg@10").mean(),
    pl.col("best:epoch/train_recall@20").mean(),
    pl.col("best:epoch/train_ndcg@20").mean(),
    pl.col("best:epoch/test_recall@20").mean(),
    pl.col("best:epoch/test_ndcg@20").mean(),
).sort(
    "l1_regularization", "l2_regularization"
).with_columns(
    pl.col("l1_regularization").cast(pl.Utf8),
    pl.col("l2_regularization").cast(pl.Utf8)
)

### Run Counts

In [61]:
experiment_summary[["l1_regularization", "l2_regularization", "num_runs"]].pivot(
    values=["num_runs"],
    index="l1_regularization",
    columns="l2_regularization"
)

/tmp/ipykernel_3771275/1305047977.py:1: DeprecationWarning: the argument `columns` for `DataFrame.pivot` is deprecated. It was renamed to `on` in version 1.0.0.
  experiment_summary[["l1_regularization", "l2_regularization", "num_runs"]].pivot(

shape: (7, 8)
┌───────────────────┬─────┬──────┬──────┬──────┬──────┬─────────┬────────┐
│ l1_regularization ┆ 0.0 ┆ 1e-9 ┆ 1e-8 ┆ 1e-7 ┆ 1e-6 ┆ 0.00001 ┆ 0.0001 │
│ ---               ┆ --- ┆ ---  ┆ ---  ┆ ---  ┆ ---  ┆ ---     ┆ ---    │
│ str               ┆ u32 ┆ u32  ┆ u32  ┆ u32  ┆ u32  ┆ u32     ┆ u32    │
╞═══════════════════╪═════╪══════╪══════╪══════╪══════╪═════════╪════════╡
│ 0.0               ┆ 7   ┆ 4    ┆ 6    ┆ 3    ┆ 5    ┆ 5       ┆ 7      │
│ 1e-9              ┆ 4   ┆ 3    ┆ 3    ┆ 2    ┆ 2    ┆ 3       ┆ 2      │
│ 1e-8              ┆ 3   ┆ 2    ┆ 5    ┆ 2    ┆ 2    ┆ 2       ┆ 2      │
│ 1e-7              ┆ 3   ┆ 2    ┆ 2    ┆ 2    ┆ 2    ┆ 2       ┆ 2      │
│ 1e-6              ┆ 8   ┆ 2    ┆ 2    ┆ 2    ┆ 4    ┆ 2       ┆ 2      │
│ 0.00001           ┆ 4   ┆ 2    ┆ 2    ┆ 2    ┆ 2    ┆ 2       ┆ 2      │
│ 0.0001            ┆ 4   ┆ 2    ┆ 2    ┆ 3    ┆ 2    ┆ 2       ┆ 2      │
└───────────────────┴─────┴──────┴──────┴──────┴──────┴─────────┴────────┘

### Best Epoch

In [62]:
(
    experiment_summary[["l1_regularization", "l2_regularization", "best:epoch/epoch"]].pivot(
        values=["best:epoch/epoch"],
        index="l1_regularization",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("l1_regularization")
    .style.background_gradient(cmap="Blues", axis=None)
    .format("{:.2f}")
)

### Best Recall@20

In [63]:
train_recall = (
        experiment_summary[["l1_regularization", "l2_regularization", "best:epoch/train_recall@20"]].pivot(
        values=["best:epoch/train_recall@20"],
        index="l1_regularization",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("l1_regularization")
)

test_recall = (
    experiment_summary[["l1_regularization", "l2_regularization", "best:epoch/test_recall@20"]].pivot(
        values=["best:epoch/test_recall@20"],
        index="l1_regularization",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("l1_regularization")
)

display(Markdown("#### Train Recall@20"))
display(train_recall.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Test Recall@20"))
display(test_recall.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Train-Test Recall@20 Difference"))
display((train_recall - test_recall).style.background_gradient(cmap="RdYlGn_r", axis=None))

#### Train Recall@20

#### Test Recall@20

#### Train-Test Recall@20 Difference

### Best NDCG@20

In [64]:
train_ndcg = (
    experiment_summary[["l1_regularization", "l2_regularization", "best:epoch/train_ndcg@20"]].pivot(
        values=["best:epoch/train_ndcg@20"],
        index="l1_regularization",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("l1_regularization")
)

test_ndcg = (
    experiment_summary[["l1_regularization", "l2_regularization", "best:epoch/test_ndcg@20"]].pivot(
        values=["best:epoch/test_ndcg@20"],
        index="l1_regularization",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("l1_regularization")
)

display(Markdown("#### Train NDCG@20"))
display(train_ndcg.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Test NDCG@20"))
display(test_ndcg.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Train-Test NDCG@20 Difference"))
display((train_ndcg - test_ndcg).style.background_gradient(cmap="RdYlGn_r", axis=None))

#### Train NDCG@20

#### Test NDCG@20

#### Train-Test NDCG@20 Difference

## ElasticNet, D=512, Shuffle = True

In [68]:
experiment_summary = experiment_runs.filter(
    pl.col("shuffle") == True,
    pl.col("embedding_dimension") == 512,
    pl.col("l1_regularization") != 1e-10, pl.col("l1_regularization") <= 1e-4,
    pl.col("l2_regularization") != 1e-10, pl.col("l2_regularization") <= 1e-4,
    pl.col("embedding_dropout_rate") == 0.0
).group_by(
    "l1_regularization", "l2_regularization"
).agg(
    pl.col("run_id").count().alias("num_runs"),
    pl.col("best:epoch/epoch").mean(),
    pl.col("best:epoch/test_recall@10").mean(),
    pl.col("best:epoch/test_ndcg@10").mean(),
    pl.col("best:epoch/train_recall@20").mean(),
    pl.col("best:epoch/train_ndcg@20").mean(),
    pl.col("best:epoch/test_recall@20").mean(),
    pl.col("best:epoch/test_ndcg@20").mean(),
).sort(
    "l1_regularization", "l2_regularization"
).with_columns(
    pl.col("l1_regularization").cast(pl.Utf8),
    pl.col("l2_regularization").cast(pl.Utf8)
)

### Run Counts

In [69]:
experiment_summary[["l1_regularization", "l2_regularization", "num_runs"]].pivot(
    values=["num_runs"],
    index="l1_regularization",
    columns="l2_regularization"
)

/tmp/ipykernel_3771275/1305047977.py:1: DeprecationWarning: the argument `columns` for `DataFrame.pivot` is deprecated. It was renamed to `on` in version 1.0.0.
  experiment_summary[["l1_regularization", "l2_regularization", "num_runs"]].pivot(

shape: (7, 8)
┌───────────────────┬─────┬──────┬──────┬──────┬──────┬─────────┬────────┐
│ l1_regularization ┆ 0.0 ┆ 1e-9 ┆ 1e-8 ┆ 1e-7 ┆ 1e-6 ┆ 0.00001 ┆ 0.0001 │
│ ---               ┆ --- ┆ ---  ┆ ---  ┆ ---  ┆ ---  ┆ ---     ┆ ---    │
│ str               ┆ u32 ┆ u32  ┆ u32  ┆ u32  ┆ u32  ┆ u32     ┆ u32    │
╞═══════════════════╪═════╪══════╪══════╪══════╪══════╪═════════╪════════╡
│ 0.0               ┆ 5   ┆ 6    ┆ 8    ┆ 6    ┆ 7    ┆ 4       ┆ 4      │
│ 1e-9              ┆ 5   ┆ 3    ┆ 4    ┆ 2    ┆ 2    ┆ 2       ┆ 2      │
│ 1e-8              ┆ 6   ┆ 2    ┆ 3    ┆ 2    ┆ 2    ┆ 2       ┆ 2      │
│ 1e-7              ┆ 7   ┆ 2    ┆ 3    ┆ 2    ┆ 4    ┆ 2       ┆ 2      │
│ 1e-6              ┆ 6   ┆ 2    ┆ 2    ┆ 3    ┆ 2    ┆ 2       ┆ 2      │
│ 0.00001           ┆ 4   ┆ 2    ┆ 2    ┆ 2    ┆ 2    ┆ 2       ┆ 2      │
│ 0.0001            ┆ 8   ┆ 2    ┆ 2    ┆ 2    ┆ 2    ┆ 2       ┆ 2      │
└───────────────────┴─────┴──────┴──────┴──────┴──────┴─────────┴────────┘

### Best Epoch

In [70]:
(
    experiment_summary[["l1_regularization", "l2_regularization", "best:epoch/epoch"]].pivot(
        values=["best:epoch/epoch"],
        index="l1_regularization",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("l1_regularization")
    .style.background_gradient(cmap="Blues", axis=None)
    .format("{:.2f}")
)

### Best Recall@20

In [71]:
train_recall = (
        experiment_summary[["l1_regularization", "l2_regularization", "best:epoch/train_recall@20"]].pivot(
        values=["best:epoch/train_recall@20"],
        index="l1_regularization",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("l1_regularization")
)

test_recall = (
    experiment_summary[["l1_regularization", "l2_regularization", "best:epoch/test_recall@20"]].pivot(
        values=["best:epoch/test_recall@20"],
        index="l1_regularization",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("l1_regularization")
)

display(Markdown("#### Train Recall@20"))
display(train_recall.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Test Recall@20"))
display(test_recall.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Train-Test Recall@20 Difference"))
display((train_recall - test_recall).style.background_gradient(cmap="RdYlGn_r", axis=None))

#### Train Recall@20

#### Test Recall@20

#### Train-Test Recall@20 Difference

### Best NDCG@20

In [72]:
train_ndcg = (
    experiment_summary[["l1_regularization", "l2_regularization", "best:epoch/train_ndcg@20"]].pivot(
        values=["best:epoch/train_ndcg@20"],
        index="l1_regularization",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("l1_regularization")
)

test_ndcg = (
    experiment_summary[["l1_regularization", "l2_regularization", "best:epoch/test_ndcg@20"]].pivot(
        values=["best:epoch/test_ndcg@20"],
        index="l1_regularization",
        on="l2_regularization"
    )
    .to_pandas()
    .set_index("l1_regularization")
)

display(Markdown("#### Train NDCG@20"))
display(train_ndcg.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Test NDCG@20"))
display(test_ndcg.style.background_gradient(cmap="RdYlGn", axis=None))

display(Markdown("#### Train-Test NDCG@20 Difference"))
display((train_ndcg - test_ndcg).style.background_gradient(cmap="RdYlGn_r", axis=None))

#### Train NDCG@20

#### Test NDCG@20

#### Train-Test NDCG@20 Difference

# Cross-GPU Training

In [46]:
experiment_runs.group_by("embedding_dimension").agg(
    pl.col("run_duration_minute").mean()
).sort("embedding_dimension")

shape: (10, 2)
┌─────────────────────┬─────────────────────┐
│ embedding_dimension ┆ run_duration_minute │
│ ---                 ┆ ---                 │
│ i64                 ┆ f64                 │
╞═════════════════════╪═════════════════════╡
│ 2                   ┆ 12.175227           │
│ 4                   ┆ 12.184093           │
│ 8                   ┆ 12.128779           │
│ 16                  ┆ 12.208779           │
│ 32                  ┆ 12.122432           │
│ 64                  ┆ 13.073482           │
│ 128                 ┆ 12.354335           │
│ 256                 ┆ 13.310513           │
│ 512                 ┆ 14.255744           │
│ 1024                ┆ 17.355111           │
└─────────────────────┴─────────────────────┘

In [47]:
experiment_runs.group_by("gpu_type").agg(
    pl.col("run_duration_minute").mean(),
    
).sort("gpu_type")

shape: (2, 2)
┌─────────────┬─────────────────────┐
│ gpu_type    ┆ run_duration_minute │
│ ---         ┆ ---                 │
│ str         ┆ f64                 │
╞═════════════╪═════════════════════╡
│ NVIDIA A10G ┆ 13.104717           │
│ NVIDIA L4   ┆ 17.202939           │
└─────────────┴─────────────────────┘

In [52]:
experiment_summary = experiment_runs.filter(
    pl.col("l2_regularization") == 0.0,
    pl.col("l1_regularization") == 0.0,
    pl.col("embedding_dropout_rate") == 0.0
).group_by("embedding_dimension", "gpu_type").agg(
    pl.col("run_id").count().alias("num_runs"),
    pl.col("best:epoch/epoch").mean(),
    pl.col("best:epoch/test_recall@10").mean(),
    pl.col("best:epoch/test_ndcg@10").mean(),
    pl.col("best:epoch/test_recall@50").mean(),
    pl.col("best:epoch/test_ndcg@50").mean(),
).sort("embedding_dimension", "gpu_type")
experiment_summary

shape: (15, 8)
┌────────────┬────────────┬──────────┬────────────┬────────────┬───────────┬───────────┬───────────┐
│ embedding_ ┆ gpu_type   ┆ num_runs ┆ best:epoch ┆ best:epoch ┆ best:epoc ┆ best:epoc ┆ best:epoc │
│ dimension  ┆ ---        ┆ ---      ┆ /epoch     ┆ /test_reca ┆ h/test_nd ┆ h/test_re ┆ h/test_nd │
│ ---        ┆ str        ┆ u32      ┆ ---        ┆ ll@10      ┆ cg@10     ┆ call@50   ┆ cg@50     │
│ i64        ┆            ┆          ┆ f64        ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆          ┆            ┆ f64        ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════════╪══════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2          ┆ NVIDIA     ┆ 11       ┆ 49.909091  ┆ 0.015237   ┆ 0.059456  ┆ 0.054251  ┆ 0.105763  │
│            ┆ A10G       ┆          ┆            ┆            ┆           ┆           ┆           │
│ 2          ┆ NVIDIA L4  ┆ 2        ┆ 54.5       ┆ 0.01585    ┆ 0.061646  ┆ 0.056766  ┆ 0.1099    │
│ 4          ┆ NVIDIA     ┆ 16       ┆ 47.75      ┆ 0.0199     ┆ 0.077285  ┆ 0.070973  ┆ 0.132605  │
│            ┆ A10G       ┆          ┆            ┆            ┆           ┆           ┆           │
│ 8          ┆ NVIDIA     ┆ 17       ┆ 50.176471  ┆ 0.021985   ┆ 0.085121  ┆ 0.078469  ┆ 0.143825  │
│            ┆ A10G       ┆          ┆            ┆            ┆           ┆           ┆           │
│ 8          ┆ NVIDIA L4  ┆ 1        ┆ 48.0       ┆ 0.022055   ┆ 0.08557   ┆ 0.078698  ┆ 0.144032  │
│ 16         ┆ NVIDIA     ┆ 15       ┆ 39.2       ┆ 0.022679   ┆ 0.087946  ┆ 0.080375  ┆ 0.14723   │
│            ┆ A10G       ┆          ┆            ┆            ┆           ┆           ┆           │
│ 16         ┆ NVIDIA L4  ┆ 1        ┆ 23.0       ┆ 0.023082   ┆ 0.089788  ┆ 0.081257  ┆ 0.148892  │
│ 32         ┆ NVIDIA     ┆ 15       ┆ 20.2       ┆ 0.022781   ┆ 0.088311  ┆ 0.080075  ┆ 0.147322  │
│            ┆ A10G       ┆          ┆            ┆            ┆           ┆           ┆           │
│ 64         ┆ NVIDIA     ┆ 13       ┆ 12.538462  ┆ 0.022715   ┆ 0.088031  ┆ 0.079253  ┆ 0.146422  │
│            ┆ A10G       ┆          ┆            ┆            ┆           ┆           ┆           │
│ 128        ┆ NVIDIA     ┆ 26       ┆ 10.653846  ┆ 0.022288   ┆ 0.086847  ┆ 0.077404  ┆ 0.14446   │
│            ┆ A10G       ┆          ┆            ┆            ┆           ┆           ┆           │
│ 128        ┆ NVIDIA L4  ┆ 1        ┆ 7.0        ┆ 0.02257    ┆ 0.08856   ┆ 0.077215  ┆ 0.145288  │
│ 256        ┆ NVIDIA     ┆ 21       ┆ 8.238095   ┆ 0.021592   ┆ 0.083876  ┆ 0.075092  ┆ 0.140285  │
│            ┆ A10G       ┆          ┆            ┆            ┆           ┆           ┆           │
│ 512        ┆ NVIDIA     ┆ 10       ┆ 2.8        ┆ 0.022356   ┆ 0.085566  ┆ 0.075475  ┆ 0.13968   │
│            ┆ A10G       ┆          ┆            ┆            ┆           ┆           ┆           │
│ 512        ┆ NVIDIA L4  ┆ 2        ┆ 6.5        ┆ 0.021995   ┆ 0.085229  ┆ 0.075376  ┆ 0.140036  │
│ 1024       ┆ NVIDIA     ┆ 14       ┆ 0.571429   ┆ 0.023215   ┆ 0.090022  ┆ 0.077101  ┆ 0.143154  │
│            ┆ A10G       ┆          ┆            ┆            ┆           ┆           ┆           │
└────────────┴────────────┴──────────┴────────────┴────────────┴───────────┴───────────┴───────────┘

In [53]:
experiment_summary[["embedding_dimension", "gpu_type", "num_runs"]].pivot(
    values=["num_runs"],
    index="embedding_dimension",
    columns="gpu_type"
)

/tmp/ipykernel_3771275/1667364229.py:1: DeprecationWarning: the argument `columns` for `DataFrame.pivot` is deprecated. It was renamed to `on` in version 1.0.0.
  experiment_summary[["embedding_dimension", "gpu_type", "num_runs"]].pivot(

shape: (10, 3)
┌─────────────────────┬─────────────┬───────────┐
│ embedding_dimension ┆ NVIDIA A10G ┆ NVIDIA L4 │
│ ---                 ┆ ---         ┆ ---       │
│ i64                 ┆ u32         ┆ u32       │
╞═════════════════════╪═════════════╪═══════════╡
│ 2                   ┆ 11          ┆ 2         │
│ 4                   ┆ 16          ┆ null      │
│ 8                   ┆ 17          ┆ 1         │
│ 16                  ┆ 15          ┆ 1         │
│ 32                  ┆ 15          ┆ null      │
│ 64                  ┆ 13          ┆ null      │
│ 128                 ┆ 26          ┆ 1         │
│ 256                 ┆ 21          ┆ null      │
│ 512                 ┆ 10          ┆ 2         │
│ 1024                ┆ 14          ┆ null      │
└─────────────────────┴─────────────┴───────────┘

In [54]:
experiment_summary[["embedding_dimension", "gpu_type", "best:epoch/test_recall@50"]].pivot(
    values=["best:epoch/test_recall@50"],
    index="embedding_dimension",
    columns="gpu_type"
)

/tmp/ipykernel_3771275/93591780.py:1: DeprecationWarning: the argument `columns` for `DataFrame.pivot` is deprecated. It was renamed to `on` in version 1.0.0.
  experiment_summary[["embedding_dimension", "gpu_type", "best:epoch/test_recall@50"]].pivot(

shape: (10, 3)
┌─────────────────────┬─────────────┬───────────┐
│ embedding_dimension ┆ NVIDIA A10G ┆ NVIDIA L4 │
│ ---                 ┆ ---         ┆ ---       │
│ i64                 ┆ f64         ┆ f64       │
╞═════════════════════╪═════════════╪═══════════╡
│ 2                   ┆ 0.054251    ┆ 0.056766  │
│ 4                   ┆ 0.070973    ┆ null      │
│ 8                   ┆ 0.078469    ┆ 0.078698  │
│ 16                  ┆ 0.080375    ┆ 0.081257  │
│ 32                  ┆ 0.080075    ┆ null      │
│ 64                  ┆ 0.079253    ┆ null      │
│ 128                 ┆ 0.077404    ┆ 0.077215  │
│ 256                 ┆ 0.075092    ┆ null      │
│ 512                 ┆ 0.075475    ┆ 0.075376  │
│ 1024                ┆ 0.077101    ┆ null      │
└─────────────────────┴─────────────┴───────────┘

In [55]:
experiment_summary[["embedding_dimension", "gpu_type", "best:epoch/test_ndcg@50"]].pivot(
    values=["best:epoch/test_ndcg@50"],
    index="embedding_dimension",
    columns="gpu_type"
)

/tmp/ipykernel_3771275/2601597168.py:1: DeprecationWarning: the argument `columns` for `DataFrame.pivot` is deprecated. It was renamed to `on` in version 1.0.0.
  experiment_summary[["embedding_dimension", "gpu_type", "best:epoch/test_ndcg@50"]].pivot(

shape: (10, 3)
┌─────────────────────┬─────────────┬───────────┐
│ embedding_dimension ┆ NVIDIA A10G ┆ NVIDIA L4 │
│ ---                 ┆ ---         ┆ ---       │
│ i64                 ┆ f64         ┆ f64       │
╞═════════════════════╪═════════════╪═══════════╡
│ 2                   ┆ 0.105763    ┆ 0.1099    │
│ 4                   ┆ 0.132605    ┆ null      │
│ 8                   ┆ 0.143825    ┆ 0.144032  │
│ 16                  ┆ 0.14723     ┆ 0.148892  │
│ 32                  ┆ 0.147322    ┆ null      │
│ 64                  ┆ 0.146422    ┆ null      │
│ 128                 ┆ 0.14446     ┆ 0.145288  │
│ 256                 ┆ 0.140285    ┆ null      │
│ 512                 ┆ 0.13968     ┆ 0.140036  │
│ 1024                ┆ 0.143154    ┆ null      │
└─────────────────────┴─────────────┴───────────┘